// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pagogo

import (
	"github.com/pago-sh/pago-go/internal/config"
	"github.com/pago-sh/pago-go/internal/hooks"
)

type CustomerPortal struct {
	BenefitGrants   *PagoBenefitGrants
	Customers       *PagoCustomers
	CustomerMeters  *PagoCustomerMeters
	Seats           *Seats
	CustomerSession *CustomerSession
	Downloadables   *Downloadables
	LicenseKeys     *PagoLicenseKeys
	Members         *PagoMembers
	Orders          *PagoOrders
	Organizations   *PagoOrganizations
	Subscriptions   *PagoSubscriptions
	Wallets         *Wallets

	rootSDK          *Pago
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newCustomerPortal(rootSDK *Pago, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *CustomerPortal {
	return &CustomerPortal{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		BenefitGrants:    newPagoBenefitGrants(rootSDK, sdkConfig, hooks),
		Customers:        newPagoCustomers(rootSDK, sdkConfig, hooks),
		CustomerMeters:   newPagoCustomerMeters(rootSDK, sdkConfig, hooks),
		Seats:            newSeats(rootSDK, sdkConfig, hooks),
		CustomerSession:  newCustomerSession(rootSDK, sdkConfig, hooks),
		Downloadables:    newDownloadables(rootSDK, sdkConfig, hooks),
		LicenseKeys:      newPagoLicenseKeys(rootSDK, sdkConfig, hooks),
		Members:          newPagoMembers(rootSDK, sdkConfig, hooks),
		Orders:           newPagoOrders(rootSDK, sdkConfig, hooks),
		Organizations:    newPagoOrganizations(rootSDK, sdkConfig, hooks),
		Subscriptions:    newPagoSubscriptions(rootSDK, sdkConfig, hooks),
		Wallets:          newWallets(rootSDK, sdkConfig, hooks),
	}
}
