// Code generated by the Pago SDK generator. DO NOT EDIT.

// Package v2026_04 is the Pago API client for version 2026-04.
package v2026_04

import (
	pago "github.com/pago-sh/pago-go"
)

// APIVersion is the API version this package targets.
const APIVersion = "2026-04"

// Client is the entry point of the Pago API for version 2026-04.
//
// Every service is reachable from here:
//
//	client := v2026_04.New(pago.WithAccessToken("..."))
//	order, err := client.Orders.Get(ctx, orderID)
type Client struct {
	base *pago.ClientBase

	// Organizations exposes the Organizations endpoints.
	Organizations *OrganizationsService
	// Subscriptions exposes the Subscriptions endpoints.
	Subscriptions *SubscriptionsService
	// Oauth2 exposes the Oauth2 endpoints.
	Oauth2 *Oauth2Service
	// Benefits exposes the Benefits endpoints.
	Benefits *BenefitsService
	// BenefitGrants exposes the BenefitGrants endpoints.
	BenefitGrants *BenefitGrantsService
	// Webhooks exposes the Webhooks endpoints.
	Webhooks *WebhooksService
	// Products exposes the Products endpoints.
	Products *ProductsService
	// Orders exposes the Orders endpoints.
	Orders *OrdersService
	// Refunds exposes the Refunds endpoints.
	Refunds *RefundsService
	// Disputes exposes the Disputes endpoints.
	Disputes *DisputesService
	// Checkouts exposes the Checkouts endpoints.
	Checkouts *CheckoutsService
	// Files exposes the Files endpoints.
	Files *FilesService
	// Metrics exposes the Metrics endpoints.
	Metrics *MetricsService
	// LicenseKeys exposes the LicenseKeys endpoints.
	LicenseKeys *LicenseKeysService
	// CheckoutLinks exposes the CheckoutLinks endpoints.
	CheckoutLinks *CheckoutLinksService
	// CustomFields exposes the CustomFields endpoints.
	CustomFields *CustomFieldsService
	// Discounts exposes the Discounts endpoints.
	Discounts *DiscountsService
	// Customers exposes the Customers endpoints.
	Customers *CustomersService
	// Members exposes the Members endpoints.
	Members *MembersService
	// CustomerPortal exposes the CustomerPortal endpoints.
	CustomerPortal *CustomerPortalService
	// CustomerSeats exposes the CustomerSeats endpoints.
	CustomerSeats *CustomerSeatsService
	// CustomerSessions exposes the CustomerSessions endpoints.
	CustomerSessions *CustomerSessionsService
	// Events exposes the Events endpoints.
	Events *EventsService
	// EventTypes exposes the EventTypes endpoints.
	EventTypes *EventTypesService
	// Meters exposes the Meters endpoints.
	Meters *MetersService
	// CustomerMeters exposes the CustomerMeters endpoints.
	CustomerMeters *CustomerMetersService
	// Payments exposes the Payments endpoints.
	Payments *PaymentsService
}

// New builds a client for API version 2026-04.
func New(options ...pago.Option) *Client {
	base := pago.NewClientBase(APIVersion, options...)
	return &Client{
		base:             base,
		Organizations:    newOrganizationsService(base),
		Subscriptions:    newSubscriptionsService(base),
		Oauth2:           newOauth2Service(base),
		Benefits:         newBenefitsService(base),
		BenefitGrants:    newBenefitGrantsService(base),
		Webhooks:         newWebhooksService(base),
		Products:         newProductsService(base),
		Orders:           newOrdersService(base),
		Refunds:          newRefundsService(base),
		Disputes:         newDisputesService(base),
		Checkouts:        newCheckoutsService(base),
		Files:            newFilesService(base),
		Metrics:          newMetricsService(base),
		LicenseKeys:      newLicenseKeysService(base),
		CheckoutLinks:    newCheckoutLinksService(base),
		CustomFields:     newCustomFieldsService(base),
		Discounts:        newDiscountsService(base),
		Customers:        newCustomersService(base),
		Members:          newMembersService(base),
		CustomerPortal:   newCustomerPortalService(base),
		CustomerSeats:    newCustomerSeatsService(base),
		CustomerSessions: newCustomerSessionsService(base),
		Events:           newEventsService(base),
		EventTypes:       newEventTypesService(base),
		Meters:           newMetersService(base),
		CustomerMeters:   newCustomerMetersService(base),
		Payments:         newPaymentsService(base),
	}
}

// Base returns the runtime client performing the HTTP requests.
func (c *Client) Base() *pago.ClientBase { return c.base }
