// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"encoding/json"
	"fmt"
	"net/http"

	pago "github.com/pago-sh/pago-go"
)

// AddMember400Error: Invalid request or member already exists.
type AddMember400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AddMember400Error) Error() string {
	return fmt.Sprintf("pago: AddMember400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AddMember400Error) Unwrap() error { return &e.APIError }

func newAddMember400Error(statusCode int, body []byte, header http.Header) error {
	err := &AddMember400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// AddMember401Error: Authentication required
type AddMember401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AddMember401Error) Error() string {
	return fmt.Sprintf("pago: AddMember401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AddMember401Error) Unwrap() error { return &e.APIError }

func newAddMember401Error(statusCode int, body []byte, header http.Header) error {
	err := &AddMember401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// AddMember403Error: Not permitted - requires owner or billing manager role
type AddMember403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AddMember403Error) Error() string {
	return fmt.Sprintf("pago: AddMember403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AddMember403Error) Unwrap() error { return &e.APIError }

func newAddMember403Error(statusCode int, body []byte, header http.Header) error {
	err := &AddMember403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// AlreadyCanceledSubscriptionError: This subscription is already revoked.
type AlreadyCanceledSubscriptionError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data AlreadyCanceledSubscription
}

// Error implements the error interface.
func (e *AlreadyCanceledSubscriptionError) Error() string {
	return fmt.Sprintf("pago: AlreadyCanceledSubscriptionError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AlreadyCanceledSubscriptionError) Unwrap() error { return &e.APIError }

func newAlreadyCanceledSubscriptionError(statusCode int, body []byte, header http.Header) error {
	err := &AlreadyCanceledSubscriptionError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// AmbiguousExternalCustomerIDError: The external customer ID matches customers in several accessible organizations.
type AmbiguousExternalCustomerIDError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data AmbiguousExternalCustomerID
}

// Error implements the error interface.
func (e *AmbiguousExternalCustomerIDError) Error() string {
	return fmt.Sprintf("pago: AmbiguousExternalCustomerIDError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AmbiguousExternalCustomerIDError) Unwrap() error { return &e.APIError }

func newAmbiguousExternalCustomerIDError(statusCode int, body []byte, header http.Header) error {
	err := &AmbiguousExternalCustomerIDError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// AssignSeat400Error: No available seats or customer already has a seat
type AssignSeat400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AssignSeat400Error) Error() string {
	return fmt.Sprintf("pago: AssignSeat400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AssignSeat400Error) Unwrap() error { return &e.APIError }

func newAssignSeat400Error(statusCode int, body []byte, header http.Header) error {
	err := &AssignSeat400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// AssignSeat401Error: Authentication required
type AssignSeat401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AssignSeat401Error) Error() string {
	return fmt.Sprintf("pago: AssignSeat401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AssignSeat401Error) Unwrap() error { return &e.APIError }

func newAssignSeat401Error(statusCode int, body []byte, header http.Header) error {
	err := &AssignSeat401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// AssignSeat403Error: Not permitted or seat-based pricing not enabled
type AssignSeat403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AssignSeat403Error) Error() string {
	return fmt.Sprintf("pago: AssignSeat403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AssignSeat403Error) Unwrap() error { return &e.APIError }

func newAssignSeat403Error(statusCode int, body []byte, header http.Header) error {
	err := &AssignSeat403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// AssignSeat404Error: Subscription, order, or customer not found
type AssignSeat404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *AssignSeat404Error) Error() string {
	return fmt.Sprintf("pago: AssignSeat404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *AssignSeat404Error) Unwrap() error { return &e.APIError }

func newAssignSeat404Error(statusCode int, body []byte, header http.Header) error {
	err := &AssignSeat404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// CannotCreateOrganizationResponseError: Forbidden
type CannotCreateOrganizationResponseError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data CannotCreateOrganizationError
}

// Error implements the error interface.
func (e *CannotCreateOrganizationResponseError) Error() string {
	return fmt.Sprintf("pago: CannotCreateOrganizationResponseError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *CannotCreateOrganizationResponseError) Unwrap() error { return &e.APIError }

func newCannotCreateOrganizationResponseError(statusCode int, body []byte, header http.Header) error {
	err := &CannotCreateOrganizationResponseError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// CheckEmailUpdate401Error: Invalid or expired verification token.
type CheckEmailUpdate401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *CheckEmailUpdate401Error) Error() string {
	return fmt.Sprintf("pago: CheckEmailUpdate401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *CheckEmailUpdate401Error) Unwrap() error { return &e.APIError }

func newCheckEmailUpdate401Error(statusCode int, body []byte, header http.Header) error {
	err := &CheckEmailUpdate401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ClaimSeat400Error: Invalid, expired, or already claimed token
type ClaimSeat400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ClaimSeat400Error) Error() string {
	return fmt.Sprintf("pago: ClaimSeat400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ClaimSeat400Error) Unwrap() error { return &e.APIError }

func newClaimSeat400Error(statusCode int, body []byte, header http.Header) error {
	err := &ClaimSeat400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ClaimSeat403Error: Seat-based pricing not enabled for organization
type ClaimSeat403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ClaimSeat403Error) Error() string {
	return fmt.Sprintf("pago: ClaimSeat403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ClaimSeat403Error) Unwrap() error { return &e.APIError }

func newClaimSeat403Error(statusCode int, body []byte, header http.Header) error {
	err := &ClaimSeat403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ClientConfirm403Error: The checkout is expired, the customer already has an active subscription, or the organization is not ready to accept payments.
type ClientConfirm403Error struct {
	pago.APIError

	// Data is the decoded error response body.
	Data CheckoutForbiddenError
}

// Error implements the error interface.
func (e *ClientConfirm403Error) Error() string {
	return fmt.Sprintf("pago: ClientConfirm403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ClientConfirm403Error) Unwrap() error { return &e.APIError }

func newClientConfirm403Error(statusCode int, body []byte, header http.Header) error {
	err := &ClientConfirm403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// ClientUpdate403Error: The checkout is expired, the customer already has an active subscription, or the organization is not ready to accept payments.
type ClientUpdate403Error struct {
	pago.APIError

	// Data is the decoded error response body.
	Data CheckoutForbiddenError
}

// Error implements the error interface.
func (e *ClientUpdate403Error) Error() string {
	return fmt.Sprintf("pago: ClientUpdate403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ClientUpdate403Error) Unwrap() error { return &e.APIError }

func newClientUpdate403Error(statusCode int, body []byte, header http.Header) error {
	err := &ClientUpdate403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// CustomerNotReadyError: Customer is not ready to confirm a payment method.
type CustomerNotReadyError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data CustomerNotReady
}

// Error implements the error interface.
func (e *CustomerNotReadyError) Error() string {
	return fmt.Sprintf("pago: CustomerNotReadyError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *CustomerNotReadyError) Unwrap() error { return &e.APIError }

func newCustomerNotReadyError(statusCode int, body []byte, header http.Header) error {
	err := &CustomerNotReadyError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// DisputeNotOpenResponseError: Conflict
type DisputeNotOpenResponseError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data DisputeNotOpenError
}

// Error implements the error interface.
func (e *DisputeNotOpenResponseError) Error() string {
	return fmt.Sprintf("pago: DisputeNotOpenResponseError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *DisputeNotOpenResponseError) Unwrap() error { return &e.APIError }

func newDisputeNotOpenResponseError(statusCode int, body []byte, header http.Header) error {
	err := &DisputeNotOpenResponseError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// ExpiredCheckoutResponseError: The checkout session is expired.
type ExpiredCheckoutResponseError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data ExpiredCheckoutError
}

// Error implements the error interface.
func (e *ExpiredCheckoutResponseError) Error() string {
	return fmt.Sprintf("pago: ExpiredCheckoutResponseError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ExpiredCheckoutResponseError) Unwrap() error { return &e.APIError }

func newExpiredCheckoutResponseError(statusCode int, body []byte, header http.Header) error {
	err := &ExpiredCheckoutResponseError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// Finalize402Error: The charge failed, or requires customer authentication (e.g. a 3DS challenge) that can't be completed off-session.
type Finalize402Error struct {
	pago.APIError

	// Data is the decoded error response body.
	Data PaymentUnion
}

// Error implements the error interface.
func (e *Finalize402Error) Error() string {
	return fmt.Sprintf("pago: Finalize402Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *Finalize402Error) Unwrap() error { return &e.APIError }

func newFinalize402Error(statusCode int, body []byte, header http.Header) error {
	err := &Finalize402Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// Finalize403Error: Off-session charges are not enabled for this organization, or its account can't currently accept payments.
type Finalize403Error struct {
	pago.APIError

	// Data is the decoded error response body.
	Data OffSessionChargesNotEnabledOrOrganizationNotReadyForPayments
}

// Error implements the error interface.
func (e *Finalize403Error) Error() string {
	return fmt.Sprintf("pago: Finalize403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *Finalize403Error) Unwrap() error { return &e.APIError }

func newFinalize403Error(statusCode int, body []byte, header http.Header) error {
	err := &Finalize403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// GetClaimInfo400Error: Invalid or expired invitation token
type GetClaimInfo400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *GetClaimInfo400Error) Error() string {
	return fmt.Sprintf("pago: GetClaimInfo400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *GetClaimInfo400Error) Unwrap() error { return &e.APIError }

func newGetClaimInfo400Error(statusCode int, body []byte, header http.Header) error {
	err := &GetClaimInfo400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// GetClaimInfo403Error: Seat-based pricing not enabled for organization
type GetClaimInfo403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *GetClaimInfo403Error) Error() string {
	return fmt.Sprintf("pago: GetClaimInfo403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *GetClaimInfo403Error) Unwrap() error { return &e.APIError }

func newGetClaimInfo403Error(statusCode int, body []byte, header http.Header) error {
	err := &GetClaimInfo403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// GetClaimInfo404Error: Seat not found
type GetClaimInfo404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *GetClaimInfo404Error) Error() string {
	return fmt.Sprintf("pago: GetClaimInfo404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *GetClaimInfo404Error) Unwrap() error { return &e.APIError }

func newGetClaimInfo404Error(statusCode int, body []byte, header http.Header) error {
	err := &GetClaimInfo404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// HTTPValidationResponseError: Validation Error
type HTTPValidationResponseError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data HTTPValidationError
}

// Error implements the error interface.
func (e *HTTPValidationResponseError) Error() string {
	return fmt.Sprintf("pago: HTTPValidationResponseError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *HTTPValidationResponseError) Unwrap() error { return &e.APIError }

func newHTTPValidationResponseError(statusCode int, body []byte, header http.Header) error {
	err := &HTTPValidationResponseError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// ListClaimedSubscriptions401Error: Authentication required
type ListClaimedSubscriptions401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ListClaimedSubscriptions401Error) Error() string {
	return fmt.Sprintf("pago: ListClaimedSubscriptions401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ListClaimedSubscriptions401Error) Unwrap() error { return &e.APIError }

func newListClaimedSubscriptions401Error(statusCode int, body []byte, header http.Header) error {
	err := &ListClaimedSubscriptions401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ListMembers401Error: Authentication required
type ListMembers401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ListMembers401Error) Error() string {
	return fmt.Sprintf("pago: ListMembers401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ListMembers401Error) Unwrap() error { return &e.APIError }

func newListMembers401Error(statusCode int, body []byte, header http.Header) error {
	err := &ListMembers401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ListMembers403Error: Not permitted - requires owner or billing manager role
type ListMembers403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ListMembers403Error) Error() string {
	return fmt.Sprintf("pago: ListMembers403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ListMembers403Error) Unwrap() error { return &e.APIError }

func newListMembers403Error(statusCode int, body []byte, header http.Header) error {
	err := &ListMembers403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ListSeats401Error: Authentication required
type ListSeats401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ListSeats401Error) Error() string {
	return fmt.Sprintf("pago: ListSeats401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ListSeats401Error) Unwrap() error { return &e.APIError }

func newListSeats401Error(statusCode int, body []byte, header http.Header) error {
	err := &ListSeats401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ListSeats403Error: Not permitted or seat-based pricing not enabled
type ListSeats403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ListSeats403Error) Error() string {
	return fmt.Sprintf("pago: ListSeats403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ListSeats403Error) Unwrap() error { return &e.APIError }

func newListSeats403Error(statusCode int, body []byte, header http.Header) error {
	err := &ListSeats403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ListSeats404Error: Subscription or order not found
type ListSeats404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ListSeats404Error) Error() string {
	return fmt.Sprintf("pago: ListSeats404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ListSeats404Error) Unwrap() error { return &e.APIError }

func newListSeats404Error(statusCode int, body []byte, header http.Header) error {
	err := &ListSeats404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ManualRetryLimitExceededError: Manual retry limit exceeded.
type ManualRetryLimitExceededError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data ManualRetryLimitExceeded
}

// Error implements the error interface.
func (e *ManualRetryLimitExceededError) Error() string {
	return fmt.Sprintf("pago: ManualRetryLimitExceededError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ManualRetryLimitExceededError) Unwrap() error { return &e.APIError }

func newManualRetryLimitExceededError(statusCode int, body []byte, header http.Header) error {
	err := &ManualRetryLimitExceededError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// MissingInvoiceBillingDetailsError: Order is missing billing name or address.
type MissingInvoiceBillingDetailsError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data MissingInvoiceBillingDetails
}

// Error implements the error interface.
func (e *MissingInvoiceBillingDetailsError) Error() string {
	return fmt.Sprintf("pago: MissingInvoiceBillingDetailsError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *MissingInvoiceBillingDetailsError) Unwrap() error { return &e.APIError }

func newMissingInvoiceBillingDetailsError(statusCode int, body []byte, header http.Header) error {
	err := &MissingInvoiceBillingDetailsError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// NotPermittedError: You don't have the permission to update this organization.
type NotPermittedError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data NotPermitted
}

// Error implements the error interface.
func (e *NotPermittedError) Error() string {
	return fmt.Sprintf("pago: NotPermittedError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *NotPermittedError) Unwrap() error { return &e.APIError }

func newNotPermittedError(statusCode int, body []byte, header http.Header) error {
	err := &NotPermittedError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// OrderNotDraftError: The order is not in `draft` status.
type OrderNotDraftError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data OrderNotDraft
}

// Error implements the error interface.
func (e *OrderNotDraftError) Error() string {
	return fmt.Sprintf("pago: OrderNotDraftError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *OrderNotDraftError) Unwrap() error { return &e.APIError }

func newOrderNotDraftError(statusCode int, body []byte, header http.Header) error {
	err := &OrderNotDraftError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// OrderNotEligibleForInvoiceError: Order is not eligible for invoice generation (invalid status).
type OrderNotEligibleForInvoiceError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data OrderNotEligibleForInvoice
}

// Error implements the error interface.
func (e *OrderNotEligibleForInvoiceError) Error() string {
	return fmt.Sprintf("pago: OrderNotEligibleForInvoiceError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *OrderNotEligibleForInvoiceError) Unwrap() error { return &e.APIError }

func newOrderNotEligibleForInvoiceError(statusCode int, body []byte, header http.Header) error {
	err := &OrderNotEligibleForInvoiceError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// OrderNotEligibleForRetryError: Order not eligible for retry or payment confirmation failed.
type OrderNotEligibleForRetryError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data OrderNotEligibleForRetry
}

// Error implements the error interface.
func (e *OrderNotEligibleForRetryError) Error() string {
	return fmt.Sprintf("pago: OrderNotEligibleForRetryError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *OrderNotEligibleForRetryError) Unwrap() error { return &e.APIError }

func newOrderNotEligibleForRetryError(statusCode int, body []byte, header http.Header) error {
	err := &OrderNotEligibleForRetryError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// PaymentAlreadyInProgressError: Payment already in progress.
type PaymentAlreadyInProgressError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data PaymentAlreadyInProgress
}

// Error implements the error interface.
func (e *PaymentAlreadyInProgressError) Error() string {
	return fmt.Sprintf("pago: PaymentAlreadyInProgressError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *PaymentAlreadyInProgressError) Unwrap() error { return &e.APIError }

func newPaymentAlreadyInProgressError(statusCode int, body []byte, header http.Header) error {
	err := &PaymentAlreadyInProgressError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// PaymentFailedError: Payment required to apply the subscription update.
type PaymentFailedError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data PaymentFailed
}

// Error implements the error interface.
func (e *PaymentFailedError) Error() string {
	return fmt.Sprintf("pago: PaymentFailedError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *PaymentFailedError) Unwrap() error { return &e.APIError }

func newPaymentFailedError(statusCode int, body []byte, header http.Header) error {
	err := &PaymentFailedError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// PaymentMethodInUseByActiveSubscriptionError: Payment method is used by active subscription(s).
type PaymentMethodInUseByActiveSubscriptionError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data PaymentMethodInUseByActiveSubscription
}

// Error implements the error interface.
func (e *PaymentMethodInUseByActiveSubscriptionError) Error() string {
	return fmt.Sprintf("pago: PaymentMethodInUseByActiveSubscriptionError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *PaymentMethodInUseByActiveSubscriptionError) Unwrap() error { return &e.APIError }

func newPaymentMethodInUseByActiveSubscriptionError(statusCode int, body []byte, header http.Header) error {
	err := &PaymentMethodInUseByActiveSubscriptionError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// PaymentMethodSetupFailedError: The card was declined while setting up the payment method.
type PaymentMethodSetupFailedError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data PaymentMethodSetupFailed
}

// Error implements the error interface.
func (e *PaymentMethodSetupFailedError) Error() string {
	return fmt.Sprintf("pago: PaymentMethodSetupFailedError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *PaymentMethodSetupFailedError) Unwrap() error { return &e.APIError }

func newPaymentMethodSetupFailedError(statusCode int, body []byte, header http.Header) error {
	err := &PaymentMethodSetupFailedError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// PaymentResponseError: The payment failed.
type PaymentResponseError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data PaymentError
}

// Error implements the error interface.
func (e *PaymentResponseError) Error() string {
	return fmt.Sprintf("pago: PaymentResponseError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *PaymentResponseError) Unwrap() error { return &e.APIError }

func newPaymentResponseError(statusCode int, body []byte, header http.Header) error {
	err := &PaymentResponseError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// RefundedAlreadyError: Order is already fully refunded.
type RefundedAlreadyError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data RefundedAlready
}

// Error implements the error interface.
func (e *RefundedAlreadyError) Error() string {
	return fmt.Sprintf("pago: RefundedAlreadyError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RefundedAlreadyError) Unwrap() error { return &e.APIError }

func newRefundedAlreadyError(statusCode int, body []byte, header http.Header) error {
	err := &RefundedAlreadyError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// RemoveMember400Error: Cannot remove the only owner.
type RemoveMember400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RemoveMember400Error) Error() string {
	return fmt.Sprintf("pago: RemoveMember400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RemoveMember400Error) Unwrap() error { return &e.APIError }

func newRemoveMember400Error(statusCode int, body []byte, header http.Header) error {
	err := &RemoveMember400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// RemoveMember401Error: Authentication required
type RemoveMember401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RemoveMember401Error) Error() string {
	return fmt.Sprintf("pago: RemoveMember401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RemoveMember401Error) Unwrap() error { return &e.APIError }

func newRemoveMember401Error(statusCode int, body []byte, header http.Header) error {
	err := &RemoveMember401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// RemoveMember403Error: Not permitted - requires owner or billing manager role
type RemoveMember403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RemoveMember403Error) Error() string {
	return fmt.Sprintf("pago: RemoveMember403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RemoveMember403Error) Unwrap() error { return &e.APIError }

func newRemoveMember403Error(statusCode int, body []byte, header http.Header) error {
	err := &RemoveMember403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// RemoveMember404Error: Member not found.
type RemoveMember404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RemoveMember404Error) Error() string {
	return fmt.Sprintf("pago: RemoveMember404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RemoveMember404Error) Unwrap() error { return &e.APIError }

func newRemoveMember404Error(statusCode int, body []byte, header http.Header) error {
	err := &RemoveMember404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ResendInvitation400Error: Seat is not pending or already claimed
type ResendInvitation400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ResendInvitation400Error) Error() string {
	return fmt.Sprintf("pago: ResendInvitation400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ResendInvitation400Error) Unwrap() error { return &e.APIError }

func newResendInvitation400Error(statusCode int, body []byte, header http.Header) error {
	err := &ResendInvitation400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ResendInvitation401Error: Authentication required
type ResendInvitation401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ResendInvitation401Error) Error() string {
	return fmt.Sprintf("pago: ResendInvitation401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ResendInvitation401Error) Unwrap() error { return &e.APIError }

func newResendInvitation401Error(statusCode int, body []byte, header http.Header) error {
	err := &ResendInvitation401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ResendInvitation403Error: Not permitted or seat-based pricing not enabled
type ResendInvitation403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ResendInvitation403Error) Error() string {
	return fmt.Sprintf("pago: ResendInvitation403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ResendInvitation403Error) Unwrap() error { return &e.APIError }

func newResendInvitation403Error(statusCode int, body []byte, header http.Header) error {
	err := &ResendInvitation403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ResendInvitation404Error: Seat not found
type ResendInvitation404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *ResendInvitation404Error) Error() string {
	return fmt.Sprintf("pago: ResendInvitation404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ResendInvitation404Error) Unwrap() error { return &e.APIError }

func newResendInvitation404Error(statusCode int, body []byte, header http.Header) error {
	err := &ResendInvitation404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// ResourceNotFoundError: Organization not found.
type ResourceNotFoundError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data ResourceNotFound
}

// Error implements the error interface.
func (e *ResourceNotFoundError) Error() string {
	return fmt.Sprintf("pago: ResourceNotFoundError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *ResourceNotFoundError) Unwrap() error { return &e.APIError }

func newResourceNotFoundError(statusCode int, body []byte, header http.Header) error {
	err := &ResourceNotFoundError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// RevokeSeat401Error: Authentication required
type RevokeSeat401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RevokeSeat401Error) Error() string {
	return fmt.Sprintf("pago: RevokeSeat401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RevokeSeat401Error) Unwrap() error { return &e.APIError }

func newRevokeSeat401Error(statusCode int, body []byte, header http.Header) error {
	err := &RevokeSeat401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// RevokeSeat403Error: Not permitted or seat-based pricing not enabled
type RevokeSeat403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RevokeSeat403Error) Error() string {
	return fmt.Sprintf("pago: RevokeSeat403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RevokeSeat403Error) Unwrap() error { return &e.APIError }

func newRevokeSeat403Error(statusCode int, body []byte, header http.Header) error {
	err := &RevokeSeat403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// RevokeSeat404Error: Seat not found
type RevokeSeat404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *RevokeSeat404Error) Error() string {
	return fmt.Sprintf("pago: RevokeSeat404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *RevokeSeat404Error) Unwrap() error { return &e.APIError }

func newRevokeSeat404Error(statusCode int, body []byte, header http.Header) error {
	err := &RevokeSeat404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// SSOEnforcementRequiresConnectionError: Cannot enforce SSO without an enabled connection.
type SSOEnforcementRequiresConnectionError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data SSOEnforcementRequiresConnection
}

// Error implements the error interface.
func (e *SSOEnforcementRequiresConnectionError) Error() string {
	return fmt.Sprintf("pago: SSOEnforcementRequiresConnectionError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *SSOEnforcementRequiresConnectionError) Unwrap() error { return &e.APIError }

func newSsoEnforcementRequiresConnectionError(statusCode int, body []byte, header http.Header) error {
	err := &SSOEnforcementRequiresConnectionError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// SubscriptionLockedError: Subscription is pending an update.
type SubscriptionLockedError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data SubscriptionLocked
}

// Error implements the error interface.
func (e *SubscriptionLockedError) Error() string {
	return fmt.Sprintf("pago: SubscriptionLockedError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *SubscriptionLockedError) Unwrap() error { return &e.APIError }

func newSubscriptionLockedError(statusCode int, body []byte, header http.Header) error {
	err := &SubscriptionLockedError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// UnauthorizedError: Not authorized to manage license key.
type UnauthorizedError struct {
	pago.APIError

	// Data is the decoded error response body.
	Data Unauthorized
}

// Error implements the error interface.
func (e *UnauthorizedError) Error() string {
	return fmt.Sprintf("pago: UnauthorizedError (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *UnauthorizedError) Unwrap() error { return &e.APIError }

func newUnauthorizedError(statusCode int, body []byte, header http.Header) error {
	err := &UnauthorizedError{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// Update403Error: The checkout is expired, the customer already has an active subscription, or the organization is not ready to accept payments.
type Update403Error struct {
	pago.APIError

	// Data is the decoded error response body.
	Data CheckoutForbiddenError
}

// Error implements the error interface.
func (e *Update403Error) Error() string {
	return fmt.Sprintf("pago: Update403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *Update403Error) Unwrap() error { return &e.APIError }

func newUpdate403Error(statusCode int, body []byte, header http.Header) error {
	err := &Update403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	_ = json.Unmarshal(body, &err.Data)
	return err
}

// Update404Error: Not Found
type Update404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *Update404Error) Error() string {
	return fmt.Sprintf("pago: Update404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *Update404Error) Unwrap() error { return &e.APIError }

func newUpdate404Error(statusCode int, body []byte, header http.Header) error {
	err := &Update404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// UpdateMember400Error: Invalid role change.
type UpdateMember400Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *UpdateMember400Error) Error() string {
	return fmt.Sprintf("pago: UpdateMember400Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *UpdateMember400Error) Unwrap() error { return &e.APIError }

func newUpdateMember400Error(statusCode int, body []byte, header http.Header) error {
	err := &UpdateMember400Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// UpdateMember401Error: Authentication required
type UpdateMember401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *UpdateMember401Error) Error() string {
	return fmt.Sprintf("pago: UpdateMember401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *UpdateMember401Error) Unwrap() error { return &e.APIError }

func newUpdateMember401Error(statusCode int, body []byte, header http.Header) error {
	err := &UpdateMember401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// UpdateMember403Error: Not permitted - requires owner or billing manager role
type UpdateMember403Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *UpdateMember403Error) Error() string {
	return fmt.Sprintf("pago: UpdateMember403Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *UpdateMember403Error) Unwrap() error { return &e.APIError }

func newUpdateMember403Error(statusCode int, body []byte, header http.Header) error {
	err := &UpdateMember403Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// UpdateMember404Error: Member not found.
type UpdateMember404Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *UpdateMember404Error) Error() string {
	return fmt.Sprintf("pago: UpdateMember404Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *UpdateMember404Error) Unwrap() error { return &e.APIError }

func newUpdateMember404Error(statusCode int, body []byte, header http.Header) error {
	err := &UpdateMember404Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// VerifyEmailUpdate401Error: Invalid or expired verification token.
type VerifyEmailUpdate401Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *VerifyEmailUpdate401Error) Error() string {
	return fmt.Sprintf("pago: VerifyEmailUpdate401Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *VerifyEmailUpdate401Error) Unwrap() error { return &e.APIError }

func newVerifyEmailUpdate401Error(statusCode int, body []byte, header http.Header) error {
	err := &VerifyEmailUpdate401Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}

// VerifyEmailUpdate422Error: Email address is already in use.
type VerifyEmailUpdate422Error struct {
	pago.APIError
}

// Error implements the error interface.
func (e *VerifyEmailUpdate422Error) Error() string {
	return fmt.Sprintf("pago: VerifyEmailUpdate422Error (%d): %s", e.StatusCode, e.Body)
}

// Unwrap exposes the underlying *pago.APIError.
func (e *VerifyEmailUpdate422Error) Unwrap() error { return &e.APIError }

func newVerifyEmailUpdate422Error(statusCode int, body []byte, header http.Header) error {
	err := &VerifyEmailUpdate422Error{
		APIError: pago.APIError{StatusCode: statusCode, Body: body, Header: header},
	}
	return err
}
