// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"testing"
	"time"

	pago "github.com/pago-sh/pago-go"
)

func TestNewBuildsEveryService(t *testing.T) {
	client := New(pago.WithAccessToken("token"))

	if client.Base() == nil {
		t.Fatal("expected a runtime client")
	}
	if client.Base().Version() != APIVersion {
		t.Fatalf("expected version %q, got %q", APIVersion, client.Base().Version())
	}
	if client.Organizations == nil {
		t.Fatal("expected the Organizations service to be built")
	}
	if client.Subscriptions == nil {
		t.Fatal("expected the Subscriptions service to be built")
	}
	if client.Oauth2 == nil {
		t.Fatal("expected the Oauth2 service to be built")
	}
	if client.Benefits == nil {
		t.Fatal("expected the Benefits service to be built")
	}
	if client.BenefitGrants == nil {
		t.Fatal("expected the BenefitGrants service to be built")
	}
	if client.Webhooks == nil {
		t.Fatal("expected the Webhooks service to be built")
	}
	if client.Products == nil {
		t.Fatal("expected the Products service to be built")
	}
	if client.Orders == nil {
		t.Fatal("expected the Orders service to be built")
	}
	if client.Refunds == nil {
		t.Fatal("expected the Refunds service to be built")
	}
	if client.Disputes == nil {
		t.Fatal("expected the Disputes service to be built")
	}
	if client.Checkouts == nil {
		t.Fatal("expected the Checkouts service to be built")
	}
	if client.Files == nil {
		t.Fatal("expected the Files service to be built")
	}
	if client.Metrics == nil {
		t.Fatal("expected the Metrics service to be built")
	}
	if client.LicenseKeys == nil {
		t.Fatal("expected the LicenseKeys service to be built")
	}
	if client.CheckoutLinks == nil {
		t.Fatal("expected the CheckoutLinks service to be built")
	}
	if client.CustomFields == nil {
		t.Fatal("expected the CustomFields service to be built")
	}
	if client.Discounts == nil {
		t.Fatal("expected the Discounts service to be built")
	}
	if client.Customers == nil {
		t.Fatal("expected the Customers service to be built")
	}
	if client.Members == nil {
		t.Fatal("expected the Members service to be built")
	}
	if client.CustomerPortal == nil {
		t.Fatal("expected the CustomerPortal service to be built")
	}
	if client.CustomerSeats == nil {
		t.Fatal("expected the CustomerSeats service to be built")
	}
	if client.CustomerSessions == nil {
		t.Fatal("expected the CustomerSessions service to be built")
	}
	if client.Events == nil {
		t.Fatal("expected the Events service to be built")
	}
	if client.EventTypes == nil {
		t.Fatal("expected the EventTypes service to be built")
	}
	if client.Meters == nil {
		t.Fatal("expected the Meters service to be built")
	}
	if client.CustomerMeters == nil {
		t.Fatal("expected the CustomerMeters service to be built")
	}
	if client.Payments == nil {
		t.Fatal("expected the Payments service to be built")
	}
}

// testWebhookSecret is a Pago endpoint secret: the "whsec_" prefix followed by
// the base64-encoded signing key.
const testWebhookSecret = "whsec_AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="

// signTestWebhook signs a body the way the Pago API does: the HMAC key is the
// base64 decoding of the secret's payload, not the secret string itself.
func signTestWebhook(body string, secret string) http.Header {
	timestamp := time.Now().Unix()
	key, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(secret, "whsec_"))
	if err != nil {
		panic("test secret is not a valid whsec_ secret: " + err.Error())
	}
	mac := hmac.New(sha256.New, key)
	mac.Write([]byte(fmt.Sprintf("msg_test.%d.%s", timestamp, body)))

	headers := http.Header{}
	headers.Set("Webhook-Id", "msg_test")
	headers.Set("Webhook-Timestamp", fmt.Sprintf("%d", timestamp))
	headers.Set("Webhook-Signature", "v1,"+base64.StdEncoding.EncodeToString(mac.Sum(nil)))
	return headers
}

func TestValidateEventReturnsATypedPayload(t *testing.T) {
	const secret = testWebhookSecret
	body := `{"type":"benefit.created"}`

	event, err := ValidateEvent([]byte(body), signTestWebhook(body, secret), secret)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if event.EventType() != "benefit.created" {
		t.Fatalf("expected benefit.created, got %q", event.EventType())
	}
	if _, ok := event.(*WebhookBenefitCreatedPayload); !ok {
		t.Fatalf("expected a *WebhookBenefitCreatedPayload, got %T", event)
	}
}

func TestValidateEventRejectsAnUnknownType(t *testing.T) {
	const secret = testWebhookSecret
	body := `{"type":"definitely.not.an.event"}`

	_, err := ValidateEvent([]byte(body), signTestWebhook(body, secret), secret)

	var unknown *pago.WebhookUnknownTypeError
	if !errors.As(err, &unknown) {
		t.Fatalf("expected a *pago.WebhookUnknownTypeError, got %v", err)
	}
}

func TestValidateEventRejectsATamperedBody(t *testing.T) {
	const secret = testWebhookSecret
	body := `{"type":"benefit.created"}`

	_, err := ValidateEvent([]byte(`{"type":"tampered"}`), signTestWebhook(body, secret), secret)

	var verification *pago.WebhookVerificationError
	if !errors.As(err, &verification) {
		t.Fatalf("expected a *pago.WebhookVerificationError, got %v", err)
	}
}

func TestParseWebhookEventDecodesEveryKnownType(t *testing.T) {
	if len(WebhookEventTypes) != 37 {
		t.Fatalf("expected 37 event types, got %d", len(WebhookEventTypes))
	}
	for eventType := range WebhookEventTypes {
		body, err := json.Marshal(map[string]string{"type": eventType})
		if err != nil {
			t.Fatal(err)
		}
		event, err := ParseWebhookEvent(body)
		if err != nil {
			t.Fatalf("%s: unexpected error: %v", eventType, err)
		}
		if event.EventType() != eventType {
			t.Fatalf("%s: decoded as %q", eventType, event.EventType())
		}
	}
}

func TestDiscriminatedUnionRoundTrips(t *testing.T) {
	payload := []byte(`{"func":"avg"}`)

	var union AggregationUnion
	if err := json.Unmarshal(payload, &union); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if union.PropertyAggregation == nil {
		t.Fatal("expected the PropertyAggregation variant to be set")
	}

	encoded, err := json.Marshal(union)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(encoded, &decoded); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if decoded["func"] != "avg" {
		t.Fatalf("expected the discriminator to survive marshalling, got %v", decoded)
	}
}

func TestUnknownUnionVariantIsPreserved(t *testing.T) {
	payload := []byte(`{"func":"variant.from.the.future","extra":1}`)

	var union AggregationUnion
	if err := json.Unmarshal(payload, &union); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	encoded, err := json.Marshal(union)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(encoded, &decoded); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if decoded["func"] != "variant.from.the.future" {
		t.Fatalf("expected an unknown variant to be preserved verbatim, got %v", decoded)
	}
}
