// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"

	pago "github.com/pago-sh/pago-go"
)

// Oauth2Service exposes the Oauth2 endpoints.
type Oauth2Service struct {
	client *pago.ClientBase

	// Clients exposes the Clients endpoints.
	Clients *Oauth2ClientsService
}

func newOauth2Service(client *pago.ClientBase) *Oauth2Service {
	return &Oauth2Service{
		client:  client,
		Clients: newOauth2ClientsService(client),
	}
}

// Authorize
func (s *Oauth2Service) Authorize(ctx context.Context) (*AuthorizeResponseUnion, error) {
	var out AuthorizeResponseUnion
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/oauth2/authorize",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RequestToken: Request an access token using a valid grant.
func (s *Oauth2Service) RequestToken(ctx context.Context) (*TokenResponse, error) {
	var out TokenResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/oauth2/token",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeToken: Revoke an access token or a refresh token.
func (s *Oauth2Service) RevokeToken(ctx context.Context) (*RevokeTokenResponse, error) {
	var out RevokeTokenResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/oauth2/revoke",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// IntrospectToken: Get information about an access token.
func (s *Oauth2Service) IntrospectToken(ctx context.Context) (*IntrospectTokenResponse, error) {
	var out IntrospectTokenResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/oauth2/introspect",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Userinfo: Get information about the authenticated user.
func (s *Oauth2Service) Userinfo(ctx context.Context) (*UserInfoUnion, error) {
	var out UserInfoUnion
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/oauth2/userinfo",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Oauth2ClientsService exposes the Oauth2.Clients endpoints.
type Oauth2ClientsService struct {
	client *pago.ClientBase

	// Oauth2 exposes the Oauth2 endpoints.
	Oauth2 *Oauth2ClientsOauth2Service
}

func newOauth2ClientsService(client *pago.ClientBase) *Oauth2ClientsService {
	return &Oauth2ClientsService{
		client: client,
		Oauth2: newOauth2ClientsOauth2Service(client),
	}
}

// Oauth2ClientsOauth2Service exposes the Oauth2.Clients.Oauth2 endpoints.
type Oauth2ClientsOauth2Service struct {
	client *pago.ClientBase
}

func newOauth2ClientsOauth2Service(client *pago.ClientBase) *Oauth2ClientsOauth2Service {
	return &Oauth2ClientsOauth2Service{
		client: client,
	}
}

// CreateClient: Create an OAuth2 client.
func (s *Oauth2ClientsOauth2Service) CreateClient(ctx context.Context, body OAuth2ClientConfiguration) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/oauth2/register",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClient: Get an OAuth2 client by Client ID.
func (s *Oauth2ClientsOauth2Service) GetClient(ctx context.Context, clientID string) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/oauth2/register/{client_id}",
		PathParams: map[string]any{
			"client_id": clientID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClient: Update an OAuth2 client.
func (s *Oauth2ClientsOauth2Service) UpdateClient(ctx context.Context, clientIDPath string, body OAuth2ClientConfigurationUpdate) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method: "PUT",
		Path:   "/v1/oauth2/register/{client_id}",
		PathParams: map[string]any{
			"client_id": clientIDPath,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteClient: Delete an OAuth2 client.
func (s *Oauth2ClientsOauth2Service) DeleteClient(ctx context.Context, clientID string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/oauth2/register/{client_id}",
		PathParams: map[string]any{
			"client_id": clientID,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, nil)
}
