// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// EventTypesService exposes the EventTypes endpoints.
type EventTypesService struct {
	client *pago.ClientBase
}

func newEventTypesService(client *pago.ClientBase) *EventTypesService {
	return &EventTypesService{
		client: client,
	}
}

// EventTypesListParams holds the query parameters of the request.
type EventTypesListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by external customer ID.
	ExternalCustomerID []string
	// Query: Query to filter event types by name or label.
	Query *string
	// RootEvents: When true, only return event types with root events (parent_id IS NULL).
	//
	// Default applied by the API: false
	RootEvents *bool
	// ParentID: Filter by specific parent event ID.
	ParentID *string
	// Source: Filter by event source (system or user).
	Source *EventSource
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-last_seen']"
	Sorting []EventTypesSortProperty
}

func (p EventTypesListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "root_events", p.RootEvents)
	pago.AddQueryValue(query, "parent_id", p.ParentID)
	pago.AddQueryValue(query, "source", p.Source)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List event types with aggregated statistics.
//
// **Scopes**: `events:read` `events:write`
func (s *EventTypesService) List(ctx context.Context, params EventTypesListParams) (*ListResourceEventTypeWithStats, error) {
	var out ListResourceEventTypeWithStats
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/event-types/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *EventTypesService) ListAutoPaging(ctx context.Context, params EventTypesListParams) iter.Seq2[EventTypeWithStats, error] {
	return func(yield func(EventTypeWithStats, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero EventTypeWithStats
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Update
//
// Update an event type's label.
//
// **Scopes**: `events:write`
func (s *EventTypesService) Update(ctx context.Context, id string, body EventTypeUpdate) (*EventType, error) {
	var out EventType
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/event-types/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newUpdate404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
