// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// MembersService exposes the Members endpoints.
type MembersService struct {
	client *pago.ClientBase
}

func newMembersService(client *pago.ClientBase) *MembersService {
	return &MembersService{
		client: client,
	}
}

// MembersListMembersParams holds the query parameters of the request.
type MembersListMembersParams struct {
	// CustomerID: Filter by customer ID.
	CustomerID *string
	// ExternalCustomerID: Filter by customer external ID.
	ExternalCustomerID *string
	// Role: Filter by member role.
	Role *MemberRole
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []MemberSortProperty
}

func (p MembersListMembersParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "role", p.Role)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// ListMembers
//
// List members with optional customer ID filter.
//
// **Scopes**: `members:read` `members:write`
func (s *MembersService) ListMembers(ctx context.Context, params MembersListMembersParams) (*ListResourceMember, error) {
	var out ListResourceMember
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/members/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMembersAutoPaging returns an iterator over every page of
// ListMembers, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *MembersService) ListMembersAutoPaging(ctx context.Context, params MembersListMembersParams) iter.Seq2[Member, error] {
	return func(yield func(Member, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListMembers(ctx, pageParams)
			if err != nil {
				var zero Member
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}
