// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CheckoutsService exposes the Checkouts endpoints.
type CheckoutsService struct {
	client *pago.ClientBase
}

func newCheckoutsService(client *pago.ClientBase) *CheckoutsService {
	return &CheckoutsService{
		client: client,
	}
}

// CheckoutsListParams holds the query parameters of the request.
type CheckoutsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by customer external ID.
	ExternalCustomerID []string
	// Status: Filter by checkout session status.
	Status []CheckoutStatus
	// Query: Filter by customer email.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []CheckoutSortProperty
}

func (p CheckoutsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "status", p.Status)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List checkout sessions.
//
// **Scopes**: `checkouts:read` `checkouts:write`
func (s *CheckoutsService) List(ctx context.Context, params CheckoutsListParams) (*ListResourceCheckout, error) {
	var out ListResourceCheckout
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/checkouts/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CheckoutsService) ListAutoPaging(ctx context.Context, params CheckoutsListParams) iter.Seq2[Checkout, error] {
	return func(yield func(Checkout, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Checkout
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a checkout session.
//
// **Scopes**: `checkouts:write`
func (s *CheckoutsService) Create(ctx context.Context, body CheckoutCreate) (*Checkout, error) {
	var out Checkout
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/checkouts/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a checkout session by ID.
//
// **Scopes**: `checkouts:read` `checkouts:write`
func (s *CheckoutsService) Get(ctx context.Context, id string) (*Checkout, error) {
	var out Checkout
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/checkouts/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update a checkout session.
//
// **Scopes**: `checkouts:write`
func (s *CheckoutsService) Update(ctx context.Context, id string, body CheckoutUpdate) (*Checkout, error) {
	var out Checkout
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/checkouts/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newUpdate403Error,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClientGet: Get a checkout session by client secret.
func (s *CheckoutsService) ClientGet(ctx context.Context, clientSecret string) (*CheckoutPublic, error) {
	var out CheckoutPublic
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/checkouts/client/{client_secret}",
		PathParams: map[string]any{
			"client_secret": clientSecret,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			410: newExpiredCheckoutResponseError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClientUpdate: Update a checkout session by client secret.
func (s *CheckoutsService) ClientUpdate(ctx context.Context, clientSecret string, body CheckoutUpdatePublic) (*CheckoutPublic, error) {
	var out CheckoutPublic
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/checkouts/client/{client_secret}",
		PathParams: map[string]any{
			"client_secret": clientSecret,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newClientUpdate403Error,
			404: newResourceNotFoundError,
			410: newExpiredCheckoutResponseError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClientConfirm
//
// Confirm a checkout session by client secret.
//
// Orders and subscriptions will be processed.
func (s *CheckoutsService) ClientConfirm(ctx context.Context, clientSecret string, body CheckoutConfirmStripe) (*CheckoutPublicConfirmed, error) {
	var out CheckoutPublicConfirmed
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/checkouts/client/{client_secret}/confirm",
		PathParams: map[string]any{
			"client_secret": clientSecret,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newPaymentResponseError,
			403: newClientConfirm403Error,
			404: newResourceNotFoundError,
			410: newExpiredCheckoutResponseError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
