// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// FilesService exposes the Files endpoints.
type FilesService struct {
	client *pago.ClientBase
}

func newFilesService(client *pago.ClientBase) *FilesService {
	return &FilesService{
		client: client,
	}
}

// FilesListParams holds the query parameters of the request.
type FilesListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Ids: Filter by file ID.
	Ids []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p FilesListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "ids", p.Ids)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// List
//
// List files.
//
// **Scopes**: `files:read` `files:write`
func (s *FilesService) List(ctx context.Context, params FilesListParams) (*ListResourceFileRead, error) {
	var out ListResourceFileRead
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/files/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *FilesService) ListAutoPaging(ctx context.Context, params FilesListParams) iter.Seq2[FileRead, error] {
	return func(yield func(FileRead, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero FileRead
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a file.
//
// **Scopes**: `files:write`
func (s *FilesService) Create(ctx context.Context, body FileCreate) (*FileUpload, error) {
	var out FileUpload
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/files/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Uploaded
//
// Complete a file upload.
//
// **Scopes**: `files:write`
func (s *FilesService) Uploaded(ctx context.Context, idPath string, body FileUploadCompleted) (*FileRead, error) {
	var out FileRead
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/files/{id}/uploaded",
		PathParams: map[string]any{
			"id": idPath,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete
//
// Delete a file.
//
// **Scopes**: `files:write`
func (s *FilesService) Delete(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/files/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a file.
//
// **Scopes**: `files:write`
func (s *FilesService) Update(ctx context.Context, id string, body FilePatch) (*FileRead, error) {
	var out FileRead
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/files/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
