// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CustomerSeatsService exposes the CustomerSeats endpoints.
type CustomerSeatsService struct {
	client *pago.ClientBase
}

func newCustomerSeatsService(client *pago.ClientBase) *CustomerSeatsService {
	return &CustomerSeatsService{
		client: client,
	}
}

// CustomerSeatsListSeatsParams holds the query parameters of the request.
type CustomerSeatsListSeatsParams struct {
	SubscriptionID *string
	OrderID        *string
}

func (p CustomerSeatsListSeatsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "subscription_id", p.SubscriptionID)
	pago.AddQueryValue(query, "order_id", p.OrderID)
	return query
}

// ListSeats: **Scopes**: `customer_seats:read`
func (s *CustomerSeatsService) ListSeats(ctx context.Context, params CustomerSeatsListSeatsParams) (*SeatsList, error) {
	var out SeatsList
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-seats",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newListSeats401Error,
			403: newListSeats403Error,
			404: newListSeats404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssignSeat: **Scopes**: `customer_seats:write`
func (s *CustomerSeatsService) AssignSeat(ctx context.Context, body SeatAssign) (*CustomerSeat, error) {
	var out CustomerSeat
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-seats",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newAssignSeat400Error,
			401: newAssignSeat401Error,
			403: newAssignSeat403Error,
			404: newAssignSeat404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeSeat: **Scopes**: `customer_seats:write`
func (s *CustomerSeatsService) RevokeSeat(ctx context.Context, seatID string) (*CustomerSeat, error) {
	var out CustomerSeat
	err := s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customer-seats/{seat_id}",
		PathParams: map[string]any{
			"seat_id": seatID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newRevokeSeat401Error,
			403: newRevokeSeat403Error,
			404: newRevokeSeat404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResendInvitation: **Scopes**: `customer_seats:write`
func (s *CustomerSeatsService) ResendInvitation(ctx context.Context, seatID string) (*CustomerSeat, error) {
	var out CustomerSeat
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/customer-seats/{seat_id}/resend",
		PathParams: map[string]any{
			"seat_id": seatID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newResendInvitation400Error,
			401: newResendInvitation401Error,
			403: newResendInvitation403Error,
			404: newResendInvitation404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetClaimInfo
func (s *CustomerSeatsService) GetClaimInfo(ctx context.Context, invitationToken string) (*SeatClaimInfo, error) {
	var out SeatClaimInfo
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-seats/claim/{invitation_token}",
		PathParams: map[string]any{
			"invitation_token": invitationToken,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newGetClaimInfo400Error,
			403: newGetClaimInfo403Error,
			404: newGetClaimInfo404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClaimSeat
func (s *CustomerSeatsService) ClaimSeat(ctx context.Context, body SeatClaim) (*CustomerSeatClaimResponse, error) {
	var out CustomerSeatClaimResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-seats/claim",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newClaimSeat400Error,
			403: newClaimSeat403Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
