// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// RefundsService exposes the Refunds endpoints.
type RefundsService struct {
	client *pago.ClientBase
}

func newRefundsService(client *pago.ClientBase) *RefundsService {
	return &RefundsService{
		client: client,
	}
}

// RefundsListParams holds the query parameters of the request.
type RefundsListParams struct {
	// ID: Filter by refund ID.
	ID []string
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// OrderID: Filter by order ID.
	OrderID []string
	// SubscriptionID: Filter by subscription ID.
	SubscriptionID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by customer external ID.
	ExternalCustomerID []string
	// Succeeded: Filter by `succeeded`.
	Succeeded *bool
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []RefundSortProperty
}

func (p RefundsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "id", p.ID)
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "order_id", p.OrderID)
	pago.AddQueryValue(query, "subscription_id", p.SubscriptionID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "succeeded", p.Succeeded)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List refunds.
//
// **Scopes**: `refunds:read` `refunds:write`
func (s *RefundsService) List(ctx context.Context, params RefundsListParams) (*ListResourceRefund, error) {
	var out ListResourceRefund
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/refunds/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *RefundsService) ListAutoPaging(ctx context.Context, params RefundsListParams) iter.Seq2[Refund, error] {
	return func(yield func(Refund, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Refund
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a refund.
//
// **Scopes**: `refunds:write`
func (s *RefundsService) Create(ctx context.Context, body RefundCreate) (*Refund, error) {
	var out Refund
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/refunds/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newRefundedAlreadyError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
