// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// DiscountsService exposes the Discounts endpoints.
type DiscountsService struct {
	client *pago.ClientBase
}

func newDiscountsService(client *pago.ClientBase) *DiscountsService {
	return &DiscountsService{
		client: client,
	}
}

// DiscountsListParams holds the query parameters of the request.
type DiscountsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Query: Filter by name.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []DiscountSortProperty
}

func (p DiscountsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List discounts.
//
// **Scopes**: `discounts:read` `discounts:write`
func (s *DiscountsService) List(ctx context.Context, params DiscountsListParams) (*ListResourceDiscount, error) {
	var out ListResourceDiscount
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/discounts/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *DiscountsService) ListAutoPaging(ctx context.Context, params DiscountsListParams) iter.Seq2[Discount, error] {
	return func(yield func(Discount, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Discount
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a discount.
//
// **Scopes**: `discounts:write`
func (s *DiscountsService) Create(ctx context.Context, body DiscountCreate) (*Discount, error) {
	var out Discount
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/discounts/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a discount by ID.
//
// **Scopes**: `discounts:read` `discounts:write`
func (s *DiscountsService) Get(ctx context.Context, id string) (*Discount, error) {
	var out Discount
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/discounts/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete
//
// Delete a discount.
//
// **Scopes**: `discounts:write`
func (s *DiscountsService) Delete(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/discounts/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a discount.
//
// **Scopes**: `discounts:write`
func (s *DiscountsService) Update(ctx context.Context, id string, body DiscountUpdate) (*Discount, error) {
	var out Discount
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/discounts/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
