// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// DisputesService exposes the Disputes endpoints.
type DisputesService struct {
	client *pago.ClientBase
}

func newDisputesService(client *pago.ClientBase) *DisputesService {
	return &DisputesService{
		client: client,
	}
}

// DisputesListParams holds the query parameters of the request.
type DisputesListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// OrderID: Filter by order ID.
	OrderID []string
	// Status: Filter by dispute status.
	Status []DisputeStatus
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []DisputeSortProperty
}

func (p DisputesListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "order_id", p.OrderID)
	pago.AddQueryValue(query, "status", p.Status)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List disputes.
//
// **Scopes**: `disputes:read` `disputes:write`
func (s *DisputesService) List(ctx context.Context, params DisputesListParams) (*ListResourceDispute, error) {
	var out ListResourceDispute
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/disputes/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *DisputesService) ListAutoPaging(ctx context.Context, params DisputesListParams) iter.Seq2[Dispute, error] {
	return func(yield func(Dispute, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Dispute
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a dispute by ID.
//
// **Scopes**: `disputes:read` `disputes:write`
func (s *DisputesService) Get(ctx context.Context, id string) (*Dispute, error) {
	var out Dispute
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/disputes/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Accept
//
// Accept a dispute, conceding the chargeback.
//
// Closes the dispute with the processor (settling it as `lost`) and records
// the merchant's decision on the dispute's support case.
//
// **Scopes**: `disputes:write`
func (s *DisputesService) Accept(ctx context.Context, id string) (*Dispute, error) {
	var out Dispute
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/disputes/{id}/accept",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newDisputeNotOpenResponseError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
