// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CustomFieldsService exposes the CustomFields endpoints.
type CustomFieldsService struct {
	client *pago.ClientBase
}

func newCustomFieldsService(client *pago.ClientBase) *CustomFieldsService {
	return &CustomFieldsService{
		client: client,
	}
}

// CustomFieldsListParams holds the query parameters of the request.
type CustomFieldsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Query: Filter by custom field name or slug.
	Query *string
	// Type: Filter by custom field type.
	Type []CustomFieldType
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['slug']"
	Sorting []CustomFieldSortProperty
}

func (p CustomFieldsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "type", p.Type)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List custom fields.
//
// **Scopes**: `custom_fields:read` `custom_fields:write`
func (s *CustomFieldsService) List(ctx context.Context, params CustomFieldsListParams) (*ListResourceCustomField, error) {
	var out ListResourceCustomField
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/custom-fields/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomFieldsService) ListAutoPaging(ctx context.Context, params CustomFieldsListParams) iter.Seq2[CustomField, error] {
	return func(yield func(CustomField, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomField
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a custom field.
//
// **Scopes**: `custom_fields:write`
func (s *CustomFieldsService) Create(ctx context.Context, body CustomFieldCreate) (*CustomField, error) {
	var out CustomField
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/custom-fields/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a custom field by ID.
//
// **Scopes**: `custom_fields:read` `custom_fields:write`
func (s *CustomFieldsService) Get(ctx context.Context, id string) (*CustomField, error) {
	var out CustomField
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/custom-fields/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete
//
// Delete a custom field.
//
// **Scopes**: `custom_fields:write`
func (s *CustomFieldsService) Delete(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/custom-fields/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a custom field.
//
// **Scopes**: `custom_fields:write`
func (s *CustomFieldsService) Update(ctx context.Context, id string, body CustomFieldUpdate) (*CustomField, error) {
	var out CustomField
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/custom-fields/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
