// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// ProductsService exposes the Products endpoints.
type ProductsService struct {
	client *pago.ClientBase
}

func newProductsService(client *pago.ClientBase) *ProductsService {
	return &ProductsService{
		client: client,
	}
}

// ProductsListParams holds the query parameters of the request.
type ProductsListParams struct {
	// ID: Filter by product ID.
	ID []string
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Query: Filter by product name.
	Query *string
	// IsArchived: Filter on archived products.
	IsArchived *bool
	// IsRecurring: Filter on recurring products. If `true`, only subscriptions tiers are returned. If `false`, only one-time purchase products are returned.
	IsRecurring *bool
	// BenefitID: Filter products granting specific benefit.
	BenefitID []string
	// Visibility: Filter by visibility.
	Visibility []ProductVisibility
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []ProductSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p ProductsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "id", p.ID)
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "is_archived", p.IsArchived)
	pago.AddQueryValue(query, "is_recurring", p.IsRecurring)
	pago.AddQueryValue(query, "benefit_id", p.BenefitID)
	pago.AddQueryValue(query, "visibility", p.Visibility)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List products.
//
// **Scopes**: `products:read` `products:write`
func (s *ProductsService) List(ctx context.Context, params ProductsListParams) (*ListResourceProduct, error) {
	var out ListResourceProduct
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/products/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *ProductsService) ListAutoPaging(ctx context.Context, params ProductsListParams) iter.Seq2[Product, error] {
	return func(yield func(Product, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Product
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a product.
//
// **Scopes**: `products:write`
func (s *ProductsService) Create(ctx context.Context, body ProductCreate) (*Product, error) {
	var out Product
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/products/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a product by ID.
//
// **Scopes**: `products:read` `products:write`
func (s *ProductsService) Get(ctx context.Context, id string) (*Product, error) {
	var out Product
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/products/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update a product.
//
// **Scopes**: `products:write`
func (s *ProductsService) Update(ctx context.Context, id string, body ProductUpdate) (*Product, error) {
	var out Product
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/products/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateBenefits
//
// Update benefits granted by a product.
//
// **Scopes**: `products:write`
func (s *ProductsService) UpdateBenefits(ctx context.Context, id string, body ProductBenefitsUpdate) (*Product, error) {
	var out Product
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/products/{id}/benefits",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
