// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// OrdersService exposes the Orders endpoints.
type OrdersService struct {
	client *pago.ClientBase
}

func newOrdersService(client *pago.ClientBase) *OrdersService {
	return &OrdersService{
		client: client,
	}
}

// OrdersListParams holds the query parameters of the request.
type OrdersListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
	// ProductBillingType: Filter by product billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
	ProductBillingType []ProductBillingType
	// DiscountID: Filter by discount ID.
	DiscountID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by customer external ID.
	ExternalCustomerID []string
	// CheckoutID: Filter by checkout ID.
	CheckoutID []string
	// SubscriptionID: Filter by subscription ID.
	SubscriptionID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []OrderSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p OrdersListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "product_billing_type", p.ProductBillingType)
	pago.AddQueryValue(query, "discount_id", p.DiscountID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "checkout_id", p.CheckoutID)
	pago.AddQueryValue(query, "subscription_id", p.SubscriptionID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List orders.
//
// **Scopes**: `orders:read`
func (s *OrdersService) List(ctx context.Context, params OrdersListParams) (*ListResourceOrder, error) {
	var out ListResourceOrder
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/orders/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *OrdersService) ListAutoPaging(ctx context.Context, params OrdersListParams) iter.Seq2[Order, error] {
	return func(yield func(Order, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Order
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a draft order for an off-session charge against a saved payment
// method. The order is created with `status=draft` and no invoice number;
// call `POST /v1/orders/{id}/finalize` to attempt the charge.
//
// The organization must have the `off_session_charges_enabled` feature flag.
//
// **Scopes**: `orders:write`
func (s *OrdersService) Create(ctx context.Context, body OrderCreate) (*Order, error) {
	var out Order
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/orders/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OrdersExportParams holds the query parameters of the request.
type OrdersExportParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
}

func (p OrdersExportParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	return query
}

// Export
//
// Export orders as a CSV file.
//
// **Scopes**: `orders:read`
func (s *OrdersService) Export(ctx context.Context, params OrdersExportParams) (string, error) {
	var out string
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/orders/export",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseText,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return "", err
	}
	return out, nil
}

// Get
//
// Get an order by ID.
//
// **Scopes**: `orders:read`
func (s *OrdersService) Get(ctx context.Context, id string) (*Order, error) {
	var out Order
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/orders/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update an order.
//
// **Scopes**: `orders:write`
func (s *OrdersService) Update(ctx context.Context, id string, body OrderUpdate) (*Order, error) {
	var out Order
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/orders/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Finalize
//
// Finalize a draft order and synchronously attempt an off-session charge.
//
// On success, the order transitions to `paid` and benefit grants fire
// before the response returns. On failure (decline, missing payment method,
// SCA challenge), the order stays in `draft` and a 4xx error is returned.
//
// The request fails with 412 if the order is not in `draft` status.
//
// **Scopes**: `orders:write`
func (s *OrdersService) Finalize(ctx context.Context, id string, body OrderFinalize) (*Order, error) {
	var out Order
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/orders/{id}/finalize",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			402: newFinalize402Error,
			403: newFinalize403Error,
			404: newResourceNotFoundError,
			412: newOrderNotDraftError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Invoice
//
// Get an order's invoice data.
//
// **Scopes**: `orders:read`
func (s *OrdersService) Invoice(ctx context.Context, id string) (*OrderInvoice, error) {
	var out OrderInvoice
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/orders/{id}/invoice",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GenerateInvoice
//
// Trigger generation of an order's invoice.
//
// **Scopes**: `orders:read`
func (s *OrdersService) GenerateInvoice(ctx context.Context, id string) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/orders/{id}/invoice",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newOrderNotEligibleForInvoiceError,
			422: newMissingInvoiceBillingDetailsError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Receipt
//
// Get a presigned URL to download an order's receipt PDF.
//
// **Scopes**: `orders:read`
func (s *OrdersService) Receipt(ctx context.Context, id string) (*OrderReceipt, error) {
	var out OrderReceipt
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/orders/{id}/receipt",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
