// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CustomerPortalService exposes the CustomerPortal endpoints.
type CustomerPortalService struct {
	client *pago.ClientBase

	// BenefitGrants exposes the BenefitGrants endpoints.
	BenefitGrants *CustomerPortalBenefitGrantsService

	// Customers exposes the Customers endpoints.
	Customers *CustomerPortalCustomersService

	// CustomerMeters exposes the CustomerMeters endpoints.
	CustomerMeters *CustomerPortalCustomerMetersService

	// Seats exposes the Seats endpoints.
	Seats *CustomerPortalSeatsService

	// CustomerSession exposes the CustomerSession endpoints.
	CustomerSession *CustomerPortalCustomerSessionService

	// Downloadables exposes the Downloadables endpoints.
	Downloadables *CustomerPortalDownloadablesService

	// LicenseKeys exposes the LicenseKeys endpoints.
	LicenseKeys *CustomerPortalLicenseKeysService

	// Members exposes the Members endpoints.
	Members *CustomerPortalMembersService

	// Orders exposes the Orders endpoints.
	Orders *CustomerPortalOrdersService

	// Organizations exposes the Organizations endpoints.
	Organizations *CustomerPortalOrganizationsService

	// Subscriptions exposes the Subscriptions endpoints.
	Subscriptions *CustomerPortalSubscriptionsService

	// Wallets exposes the Wallets endpoints.
	Wallets *CustomerPortalWalletsService
}

func newCustomerPortalService(client *pago.ClientBase) *CustomerPortalService {
	return &CustomerPortalService{
		client:          client,
		BenefitGrants:   newCustomerPortalBenefitGrantsService(client),
		Customers:       newCustomerPortalCustomersService(client),
		CustomerMeters:  newCustomerPortalCustomerMetersService(client),
		Seats:           newCustomerPortalSeatsService(client),
		CustomerSession: newCustomerPortalCustomerSessionService(client),
		Downloadables:   newCustomerPortalDownloadablesService(client),
		LicenseKeys:     newCustomerPortalLicenseKeysService(client),
		Members:         newCustomerPortalMembersService(client),
		Orders:          newCustomerPortalOrdersService(client),
		Organizations:   newCustomerPortalOrganizationsService(client),
		Subscriptions:   newCustomerPortalSubscriptionsService(client),
		Wallets:         newCustomerPortalWalletsService(client),
	}
}

// CustomerPortalBenefitGrantsService exposes the CustomerPortal.BenefitGrants endpoints.
type CustomerPortalBenefitGrantsService struct {
	client *pago.ClientBase
}

func newCustomerPortalBenefitGrantsService(client *pago.ClientBase) *CustomerPortalBenefitGrantsService {
	return &CustomerPortalBenefitGrantsService{
		client: client,
	}
}

// CustomerPortalBenefitGrantsListParams holds the query parameters of the request.
type CustomerPortalBenefitGrantsListParams struct {
	// Query: Filter by benefit description.
	Query *string
	// Type: Filter by benefit type.
	Type []BenefitType
	// BenefitID: Filter by benefit ID.
	BenefitID []string
	// CheckoutID: Filter by checkout ID.
	CheckoutID []string
	// OrderID: Filter by order ID.
	OrderID []string
	// SubscriptionID: Filter by subscription ID.
	SubscriptionID []string
	// MemberID: Filter by member ID.
	MemberID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['product_benefit', '-granted_at']"
	Sorting []CustomerBenefitGrantSortProperty
}

func (p CustomerPortalBenefitGrantsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "type", p.Type)
	pago.AddQueryValue(query, "benefit_id", p.BenefitID)
	pago.AddQueryValue(query, "checkout_id", p.CheckoutID)
	pago.AddQueryValue(query, "order_id", p.OrderID)
	pago.AddQueryValue(query, "subscription_id", p.SubscriptionID)
	pago.AddQueryValue(query, "member_id", p.MemberID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List benefits grants of the authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalBenefitGrantsService) List(ctx context.Context, params CustomerPortalBenefitGrantsListParams) (*ListResourceCustomerBenefitGrant, error) {
	var out ListResourceCustomerBenefitGrant
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/benefit-grants/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalBenefitGrantsService) ListAutoPaging(ctx context.Context, params CustomerPortalBenefitGrantsListParams) iter.Seq2[CustomerBenefitGrant, error] {
	return func(yield func(CustomerBenefitGrant, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomerBenefitGrant
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a benefit grant by ID for the authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalBenefitGrantsService) Get(ctx context.Context, id string) (*CustomerBenefitGrant, error) {
	var out CustomerBenefitGrant
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/benefit-grants/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update a benefit grant for the authenticated customer.
//
// **Scopes**: `customer_portal:write`
func (s *CustomerPortalBenefitGrantsService) Update(ctx context.Context, id string, body CustomerBenefitGrantUpdate) (*CustomerBenefitGrant, error) {
	var out CustomerBenefitGrant
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customer-portal/benefit-grants/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalCustomersService exposes the CustomerPortal.Customers endpoints.
type CustomerPortalCustomersService struct {
	client *pago.ClientBase
}

func newCustomerPortalCustomersService(client *pago.ClientBase) *CustomerPortalCustomersService {
	return &CustomerPortalCustomersService{
		client: client,
	}
}

// Get
//
// Get authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalCustomersService) Get(ctx context.Context) (*CustomerPortalCustomer, error) {
	var out CustomerPortalCustomer
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/customers/me",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update: Update authenticated customer.
func (s *CustomerPortalCustomersService) Update(ctx context.Context, body CustomerPortalCustomerUpdate) (*CustomerPortalCustomer, error) {
	var out CustomerPortalCustomer
	err := s.client.Do(ctx, pago.Request{
		Method:       "PATCH",
		Path:         "/v1/customer-portal/customers/me",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalCustomersListPaymentMethodsParams holds the query parameters of the request.
type CustomerPortalCustomersListPaymentMethodsParams struct {
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomerPortalCustomersListPaymentMethodsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListPaymentMethods: Get saved payment methods of the authenticated customer.
func (s *CustomerPortalCustomersService) ListPaymentMethods(ctx context.Context, params CustomerPortalCustomersListPaymentMethodsParams) (*ListResourceCustomerPaymentMethod, error) {
	var out ListResourceCustomerPaymentMethod
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/customers/me/payment-methods",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPaymentMethodsAutoPaging returns an iterator over every page of
// ListPaymentMethods, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalCustomersService) ListPaymentMethodsAutoPaging(ctx context.Context, params CustomerPortalCustomersListPaymentMethodsParams) iter.Seq2[CustomerPaymentMethod, error] {
	return func(yield func(CustomerPaymentMethod, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListPaymentMethods(ctx, pageParams)
			if err != nil {
				var zero CustomerPaymentMethod
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// AddPaymentMethod: Add a payment method to the authenticated customer.
func (s *CustomerPortalCustomersService) AddPaymentMethod(ctx context.Context, body CustomerPaymentMethodCreate) (*CustomerPaymentMethodCreateResponse, error) {
	var out CustomerPaymentMethodCreateResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/customers/me/payment-methods",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newPaymentMethodSetupFailedError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ConfirmPaymentMethod: Confirm a payment method for the authenticated customer.
func (s *CustomerPortalCustomersService) ConfirmPaymentMethod(ctx context.Context, body CustomerPaymentMethodConfirm) (*CustomerPaymentMethodCreateResponse, error) {
	var out CustomerPaymentMethodCreateResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/customers/me/payment-methods/confirm",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newCustomerNotReadyError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePaymentMethod: Delete a payment method from the authenticated customer.
func (s *CustomerPortalCustomersService) DeletePaymentMethod(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customer-portal/customers/me/payment-methods/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			400: newPaymentMethodInUseByActiveSubscriptionError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// RequestEmailUpdate: Request an email change for the authenticated customer.
func (s *CustomerPortalCustomersService) RequestEmailUpdate(ctx context.Context, body CustomerEmailUpdateRequest) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/customers/me/email-update/request",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerPortalCustomersCheckEmailUpdateParams holds the query parameters of the request.
type CustomerPortalCustomersCheckEmailUpdateParams struct {
	Token string
}

func (p CustomerPortalCustomersCheckEmailUpdateParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "token", p.Token)
	return query
}

// CheckEmailUpdate: Check if an email change verification token is still valid.
func (s *CustomerPortalCustomersService) CheckEmailUpdate(ctx context.Context, params CustomerPortalCustomersCheckEmailUpdateParams) error {
	return s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/customers/me/email-update/check",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			401: newCheckEmailUpdate401Error,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// VerifyEmailUpdate: Verify an email change using the token from the verification email.
func (s *CustomerPortalCustomersService) VerifyEmailUpdate(ctx context.Context, body CustomerEmailUpdateVerifyRequest) (*CustomerEmailUpdateVerifyResponse, error) {
	var out CustomerEmailUpdateVerifyResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/customers/me/email-update/verify",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newVerifyEmailUpdate401Error,
			422: newVerifyEmailUpdate422Error,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalCustomerMetersService exposes the CustomerPortal.CustomerMeters endpoints.
type CustomerPortalCustomerMetersService struct {
	client *pago.ClientBase
}

func newCustomerPortalCustomerMetersService(client *pago.ClientBase) *CustomerPortalCustomerMetersService {
	return &CustomerPortalCustomerMetersService{
		client: client,
	}
}

// CustomerPortalCustomerMetersListParams holds the query parameters of the request.
type CustomerPortalCustomerMetersListParams struct {
	// MeterID: Filter by meter ID.
	MeterID []string
	// Query: Filter by meter name.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-modified_at']"
	Sorting []CustomerCustomerMeterSortProperty
}

func (p CustomerPortalCustomerMetersListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "meter_id", p.MeterID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List meters of the authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalCustomerMetersService) List(ctx context.Context, params CustomerPortalCustomerMetersListParams) (*ListResourceCustomerCustomerMeter, error) {
	var out ListResourceCustomerCustomerMeter
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/meters/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalCustomerMetersService) ListAutoPaging(ctx context.Context, params CustomerPortalCustomerMetersListParams) iter.Seq2[CustomerCustomerMeter, error] {
	return func(yield func(CustomerCustomerMeter, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomerCustomerMeter
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a meter by ID for the authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalCustomerMetersService) Get(ctx context.Context, id string) (*CustomerCustomerMeter, error) {
	var out CustomerCustomerMeter
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/meters/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalSeatsService exposes the CustomerPortal.Seats endpoints.
type CustomerPortalSeatsService struct {
	client *pago.ClientBase
}

func newCustomerPortalSeatsService(client *pago.ClientBase) *CustomerPortalSeatsService {
	return &CustomerPortalSeatsService{
		client: client,
	}
}

// CustomerPortalSeatsListSeatsParams holds the query parameters of the request.
type CustomerPortalSeatsListSeatsParams struct {
	// SubscriptionID: Subscription ID
	SubscriptionID *string
	// OrderID: Order ID
	OrderID *string
}

func (p CustomerPortalSeatsListSeatsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "subscription_id", p.SubscriptionID)
	pago.AddQueryValue(query, "order_id", p.OrderID)
	return query
}

// ListSeats: **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalSeatsService) ListSeats(ctx context.Context, params CustomerPortalSeatsListSeatsParams) (*SeatsList, error) {
	var out SeatsList
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/seats",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newListSeats401Error,
			403: newListSeats403Error,
			404: newListSeats404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssignSeat
func (s *CustomerPortalSeatsService) AssignSeat(ctx context.Context, body CustomerSeatAssign) (*CustomerSeat, error) {
	var out CustomerSeat
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/seats",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newAssignSeat400Error,
			401: newAssignSeat401Error,
			403: newAssignSeat403Error,
			404: newAssignSeat404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeSeat
func (s *CustomerPortalSeatsService) RevokeSeat(ctx context.Context, seatID string) (*CustomerSeat, error) {
	var out CustomerSeat
	err := s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customer-portal/seats/{seat_id}",
		PathParams: map[string]any{
			"seat_id": seatID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newRevokeSeat401Error,
			403: newRevokeSeat403Error,
			404: newRevokeSeat404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResendInvitation
func (s *CustomerPortalSeatsService) ResendInvitation(ctx context.Context, seatID string) (*CustomerSeat, error) {
	var out CustomerSeat
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/customer-portal/seats/{seat_id}/resend",
		PathParams: map[string]any{
			"seat_id": seatID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newResendInvitation400Error,
			401: newResendInvitation401Error,
			403: newResendInvitation403Error,
			404: newResendInvitation404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalSeatsListClaimedSubscriptionsParams holds the query parameters of the request.
type CustomerPortalSeatsListClaimedSubscriptionsParams struct {
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomerPortalSeatsListClaimedSubscriptionsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListClaimedSubscriptions
//
// List all subscriptions where the authenticated customer has claimed a seat.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalSeatsService) ListClaimedSubscriptions(ctx context.Context, params CustomerPortalSeatsListClaimedSubscriptionsParams) (*ListResourceCustomerSubscription, error) {
	var out ListResourceCustomerSubscription
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/seats/subscriptions",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newListClaimedSubscriptions401Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListClaimedSubscriptionsAutoPaging returns an iterator over every page of
// ListClaimedSubscriptions, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalSeatsService) ListClaimedSubscriptionsAutoPaging(ctx context.Context, params CustomerPortalSeatsListClaimedSubscriptionsParams) iter.Seq2[CustomerSubscription, error] {
	return func(yield func(CustomerSubscription, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListClaimedSubscriptions(ctx, pageParams)
			if err != nil {
				var zero CustomerSubscription
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// CustomerPortalCustomerSessionService exposes the CustomerPortal.CustomerSession endpoints.
type CustomerPortalCustomerSessionService struct {
	client *pago.ClientBase
}

func newCustomerPortalCustomerSessionService(client *pago.ClientBase) *CustomerPortalCustomerSessionService {
	return &CustomerPortalCustomerSessionService{
		client: client,
	}
}

// Introspect
//
// Introspect the current session and return its information.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalCustomerSessionService) Introspect(ctx context.Context) (*CustomerCustomerSession, error) {
	var out CustomerCustomerSession
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/customer-session/introspect",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAuthenticatedUser
//
// Get information about the currently authenticated portal user.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalCustomerSessionService) GetAuthenticatedUser(ctx context.Context) (*PortalAuthenticatedUser, error) {
	var out PortalAuthenticatedUser
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/customer-session/user",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalDownloadablesService exposes the CustomerPortal.Downloadables endpoints.
type CustomerPortalDownloadablesService struct {
	client *pago.ClientBase
}

func newCustomerPortalDownloadablesService(client *pago.ClientBase) *CustomerPortalDownloadablesService {
	return &CustomerPortalDownloadablesService{
		client: client,
	}
}

// CustomerPortalDownloadablesListParams holds the query parameters of the request.
type CustomerPortalDownloadablesListParams struct {
	// BenefitID: Filter by benefit ID.
	BenefitID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomerPortalDownloadablesListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "benefit_id", p.BenefitID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// List: **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalDownloadablesService) List(ctx context.Context, params CustomerPortalDownloadablesListParams) (*ListResourceDownloadableRead, error) {
	var out ListResourceDownloadableRead
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/downloadables/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalDownloadablesService) ListAutoPaging(ctx context.Context, params CustomerPortalDownloadablesListParams) iter.Seq2[DownloadableRead, error] {
	return func(yield func(DownloadableRead, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero DownloadableRead
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// CustomerPortalLicenseKeysService exposes the CustomerPortal.LicenseKeys endpoints.
type CustomerPortalLicenseKeysService struct {
	client *pago.ClientBase
}

func newCustomerPortalLicenseKeysService(client *pago.ClientBase) *CustomerPortalLicenseKeysService {
	return &CustomerPortalLicenseKeysService{
		client: client,
	}
}

// CustomerPortalLicenseKeysListParams holds the query parameters of the request.
type CustomerPortalLicenseKeysListParams struct {
	// BenefitID: Filter by a specific benefit
	BenefitID *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomerPortalLicenseKeysListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "benefit_id", p.BenefitID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// List: **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalLicenseKeysService) List(ctx context.Context, params CustomerPortalLicenseKeysListParams) (*ListResourceLicenseKeyRead, error) {
	var out ListResourceLicenseKeyRead
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/license-keys/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newUnauthorizedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalLicenseKeysService) ListAutoPaging(ctx context.Context, params CustomerPortalLicenseKeysListParams) iter.Seq2[LicenseKeyRead, error] {
	return func(yield func(LicenseKeyRead, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero LicenseKeyRead
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a license key.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalLicenseKeysService) Get(ctx context.Context, id string) (*LicenseKeyWithActivations, error) {
	var out LicenseKeyWithActivations
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/license-keys/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Validate
//
// Validate a license key.
//
// > This endpoint doesn't require authentication and can be safely used on a public
// > client, like a desktop application or a mobile app.
// > If you plan to validate a license key on a server, use the `/v1/license-keys/validate`
// > endpoint instead.
func (s *CustomerPortalLicenseKeysService) Validate(ctx context.Context, body LicenseKeyValidate) (*ValidatedLicenseKey, error) {
	var out ValidatedLicenseKey
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/license-keys/validate",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Activate
//
// Activate a license key instance.
//
// > This endpoint doesn't require authentication and can be safely used on a public
// > client, like a desktop application or a mobile app.
// > If you plan to validate a license key on a server, use the `/v1/license-keys/activate`
// > endpoint instead.
func (s *CustomerPortalLicenseKeysService) Activate(ctx context.Context, body LicenseKeyActivate) (*LicenseKeyActivationRead, error) {
	var out LicenseKeyActivationRead
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/license-keys/activate",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Deactivate
//
// Deactivate a license key instance.
//
// > This endpoint doesn't require authentication and can be safely used on a public
// > client, like a desktop application or a mobile app.
// > If you plan to validate a license key on a server, use the `/v1/license-keys/deactivate`
// > endpoint instead.
func (s *CustomerPortalLicenseKeysService) Deactivate(ctx context.Context, body LicenseKeyDeactivate) error {
	return s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/license-keys/deactivate",
		Body:         body,
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// CustomerPortalMembersService exposes the CustomerPortal.Members endpoints.
type CustomerPortalMembersService struct {
	client *pago.ClientBase
}

func newCustomerPortalMembersService(client *pago.ClientBase) *CustomerPortalMembersService {
	return &CustomerPortalMembersService{
		client: client,
	}
}

// CustomerPortalMembersListMembersParams holds the query parameters of the request.
type CustomerPortalMembersListMembersParams struct {
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomerPortalMembersListMembersParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListMembers
//
// List all members of the customer's team.
//
// Only available to owners and billing managers of team customers.
func (s *CustomerPortalMembersService) ListMembers(ctx context.Context, params CustomerPortalMembersListMembersParams) (*ListResourceCustomerPortalMember, error) {
	var out ListResourceCustomerPortalMember
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/members",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newListMembers401Error,
			403: newListMembers403Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMembersAutoPaging returns an iterator over every page of
// ListMembers, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalMembersService) ListMembersAutoPaging(ctx context.Context, params CustomerPortalMembersListMembersParams) iter.Seq2[CustomerPortalMember, error] {
	return func(yield func(CustomerPortalMember, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListMembers(ctx, pageParams)
			if err != nil {
				var zero CustomerPortalMember
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// AddMember
//
// Add a new member to the customer's team.
//
// Only available to owners and billing managers of team customers.
//
// Rules:
// - Cannot add a member with the owner role (there must be exactly one owner)
// - If a member with this email already exists, the existing member is returned
func (s *CustomerPortalMembersService) AddMember(ctx context.Context, body CustomerPortalMemberCreate) (*CustomerPortalMember, error) {
	var out CustomerPortalMember
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-portal/members",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newAddMember400Error,
			401: newAddMember401Error,
			403: newAddMember403Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveMember
//
// Remove a member from the team.
//
// Only available to owners and billing managers of team customers.
//
// Rules:
// - Cannot remove yourself
// - Cannot remove the only owner
func (s *CustomerPortalMembersService) RemoveMember(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customer-portal/members/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			400: newRemoveMember400Error,
			401: newRemoveMember401Error,
			403: newRemoveMember403Error,
			404: newRemoveMember404Error,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// UpdateMember
//
// Update a member's name or role.
//
// Only available to owners and billing managers of team customers.
//
// Rules:
// - Cannot modify your own role (to prevent self-demotion)
// - Customer must have exactly one owner at all times
func (s *CustomerPortalMembersService) UpdateMember(ctx context.Context, id string, body CustomerPortalMemberUpdate) (*CustomerPortalMember, error) {
	var out CustomerPortalMember
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customer-portal/members/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			400: newUpdateMember400Error,
			401: newUpdateMember401Error,
			403: newUpdateMember403Error,
			404: newUpdateMember404Error,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalOrdersService exposes the CustomerPortal.Orders endpoints.
type CustomerPortalOrdersService struct {
	client *pago.ClientBase
}

func newCustomerPortalOrdersService(client *pago.ClientBase) *CustomerPortalOrdersService {
	return &CustomerPortalOrdersService{
		client: client,
	}
}

// CustomerPortalOrdersListParams holds the query parameters of the request.
type CustomerPortalOrdersListParams struct {
	// ProductID: Filter by product ID.
	ProductID []string
	// ProductBillingType: Filter by product billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
	ProductBillingType []ProductBillingType
	// SubscriptionID: Filter by subscription ID.
	SubscriptionID []string
	// Query: Search by product or organization name.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []CustomerOrderSortProperty
}

func (p CustomerPortalOrdersListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "product_billing_type", p.ProductBillingType)
	pago.AddQueryValue(query, "subscription_id", p.SubscriptionID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List: List orders of the authenticated customer.
func (s *CustomerPortalOrdersService) List(ctx context.Context, params CustomerPortalOrdersListParams) (*ListResourceCustomerOrder, error) {
	var out ListResourceCustomerOrder
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/orders/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalOrdersService) ListAutoPaging(ctx context.Context, params CustomerPortalOrdersListParams) iter.Seq2[CustomerOrder, error] {
	return func(yield func(CustomerOrder, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomerOrder
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get: Get an order by ID for the authenticated customer.
func (s *CustomerPortalOrdersService) Get(ctx context.Context, id string) (*CustomerOrder, error) {
	var out CustomerOrder
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/orders/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update: Update an order for the authenticated customer.
func (s *CustomerPortalOrdersService) Update(ctx context.Context, id string, body CustomerOrderUpdate) (*CustomerOrder, error) {
	var out CustomerOrder
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customer-portal/orders/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Invoice: Get an order's invoice data.
func (s *CustomerPortalOrdersService) Invoice(ctx context.Context, id string) (*CustomerOrderInvoice, error) {
	var out CustomerOrderInvoice
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/orders/{id}/invoice",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GenerateInvoice: Trigger generation of an order's invoice.
func (s *CustomerPortalOrdersService) GenerateInvoice(ctx context.Context, id string) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/customer-portal/orders/{id}/invoice",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newOrderNotEligibleForInvoiceError,
			422: newMissingInvoiceBillingDetailsError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Receipt: Get a presigned URL to download an order's receipt PDF.
func (s *CustomerPortalOrdersService) Receipt(ctx context.Context, id string) (*CustomerOrderReceipt, error) {
	var out CustomerOrderReceipt
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/orders/{id}/receipt",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPaymentStatus: Get the current payment status for an order.
func (s *CustomerPortalOrdersService) GetPaymentStatus(ctx context.Context, id string) (*CustomerOrderPaymentStatus, error) {
	var out CustomerOrderPaymentStatus
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/orders/{id}/payment-status",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ConfirmRetryPayment: Confirm a retry payment using a Stripe confirmation token.
func (s *CustomerPortalOrdersService) ConfirmRetryPayment(ctx context.Context, id string, body CustomerOrderConfirmPayment) (*CustomerOrderPaymentConfirmation, error) {
	var out CustomerOrderPaymentConfirmation
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/customer-portal/orders/{id}/confirm-payment",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newPaymentAlreadyInProgressError,
			422: newOrderNotEligibleForRetryError,
			429: newManualRetryLimitExceededError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalOrganizationsService exposes the CustomerPortal.Organizations endpoints.
type CustomerPortalOrganizationsService struct {
	client *pago.ClientBase
}

func newCustomerPortalOrganizationsService(client *pago.ClientBase) *CustomerPortalOrganizationsService {
	return &CustomerPortalOrganizationsService{
		client: client,
	}
}

// Get: Get a customer portal's organization by slug.
func (s *CustomerPortalOrganizationsService) Get(ctx context.Context, slug string) (*CustomerOrganizationData, error) {
	var out CustomerOrganizationData
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/organizations/{slug}",
		PathParams: map[string]any{
			"slug": slug,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalSubscriptionsService exposes the CustomerPortal.Subscriptions endpoints.
type CustomerPortalSubscriptionsService struct {
	client *pago.ClientBase
}

func newCustomerPortalSubscriptionsService(client *pago.ClientBase) *CustomerPortalSubscriptionsService {
	return &CustomerPortalSubscriptionsService{
		client: client,
	}
}

// CustomerPortalSubscriptionsListParams holds the query parameters of the request.
type CustomerPortalSubscriptionsListParams struct {
	// ProductID: Filter by product ID.
	ProductID []string
	// Active: Filter by active or cancelled subscription.
	Active *bool
	// Query: Search by product or organization name.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-started_at']"
	Sorting []CustomerSubscriptionSortProperty
}

func (p CustomerPortalSubscriptionsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "active", p.Active)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List subscriptions of the authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalSubscriptionsService) List(ctx context.Context, params CustomerPortalSubscriptionsListParams) (*ListResourceCustomerSubscription, error) {
	var out ListResourceCustomerSubscription
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/subscriptions/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalSubscriptionsService) ListAutoPaging(ctx context.Context, params CustomerPortalSubscriptionsListParams) iter.Seq2[CustomerSubscription, error] {
	return func(yield func(CustomerSubscription, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomerSubscription
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a subscription for the authenticated customer.
//
// **Scopes**: `customer_portal:read` `customer_portal:write`
func (s *CustomerPortalSubscriptionsService) Get(ctx context.Context, id string) (*CustomerSubscription, error) {
	var out CustomerSubscription
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/subscriptions/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Cancel: Cancel a subscription of the authenticated customer.
func (s *CustomerPortalSubscriptionsService) Cancel(ctx context.Context, id string) (*CustomerSubscription, error) {
	var out CustomerSubscription
	err := s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customer-portal/subscriptions/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newAlreadyCanceledSubscriptionError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update: Update a subscription of the authenticated customer.
func (s *CustomerPortalSubscriptionsService) Update(ctx context.Context, id string, body CustomerSubscriptionUpdate) (*CustomerSubscription, error) {
	var out CustomerSubscription
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customer-portal/subscriptions/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			402: newPaymentFailedError,
			403: newUpdate403Error,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomerPortalWalletsService exposes the CustomerPortal.Wallets endpoints.
type CustomerPortalWalletsService struct {
	client *pago.ClientBase
}

func newCustomerPortalWalletsService(client *pago.ClientBase) *CustomerPortalWalletsService {
	return &CustomerPortalWalletsService{
		client: client,
	}
}

// CustomerPortalWalletsListParams holds the query parameters of the request.
type CustomerPortalWalletsListParams struct {
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []CustomerWalletSortProperty
}

func (p CustomerPortalWalletsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List: List wallets of the authenticated customer.
func (s *CustomerPortalWalletsService) List(ctx context.Context, params CustomerPortalWalletsListParams) (*ListResourceCustomerWallet, error) {
	var out ListResourceCustomerWallet
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-portal/wallets/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerPortalWalletsService) ListAutoPaging(ctx context.Context, params CustomerPortalWalletsListParams) iter.Seq2[CustomerWallet, error] {
	return func(yield func(CustomerWallet, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomerWallet
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get: Get a wallet by ID for the authenticated customer.
func (s *CustomerPortalWalletsService) Get(ctx context.Context, id string) (*CustomerWallet, error) {
	var out CustomerWallet
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-portal/wallets/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
