// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// WebhooksService exposes the Webhooks endpoints.
type WebhooksService struct {
	client *pago.ClientBase
}

func newWebhooksService(client *pago.ClientBase) *WebhooksService {
	return &WebhooksService{
		client: client,
	}
}

// WebhooksListWebhookEndpointsParams holds the query parameters of the request.
type WebhooksListWebhookEndpointsParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p WebhooksListWebhookEndpointsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListWebhookEndpoints
//
// List webhook endpoints.
//
// **Scopes**: `webhooks:read` `webhooks:write`
func (s *WebhooksService) ListWebhookEndpoints(ctx context.Context, params WebhooksListWebhookEndpointsParams) (*ListResourceWebhookEndpoint, error) {
	var out ListResourceWebhookEndpoint
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/webhooks/endpoints",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWebhookEndpointsAutoPaging returns an iterator over every page of
// ListWebhookEndpoints, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *WebhooksService) ListWebhookEndpointsAutoPaging(ctx context.Context, params WebhooksListWebhookEndpointsParams) iter.Seq2[WebhookEndpoint, error] {
	return func(yield func(WebhookEndpoint, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListWebhookEndpoints(ctx, pageParams)
			if err != nil {
				var zero WebhookEndpoint
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// CreateWebhookEndpoint
//
// Create a webhook endpoint.
//
// **Scopes**: `webhooks:write`
func (s *WebhooksService) CreateWebhookEndpoint(ctx context.Context, body WebhookEndpointCreate) (*WebhookEndpoint, error) {
	var out WebhookEndpoint
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/webhooks/endpoints",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWebhookEndpoint
//
// Get a webhook endpoint by ID.
//
// **Scopes**: `webhooks:read` `webhooks:write`
func (s *WebhooksService) GetWebhookEndpoint(ctx context.Context, id string) (*WebhookEndpoint, error) {
	var out WebhookEndpoint
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/webhooks/endpoints/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteWebhookEndpoint
//
// Delete a webhook endpoint.
//
// **Scopes**: `webhooks:write`
func (s *WebhooksService) DeleteWebhookEndpoint(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/webhooks/endpoints/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// UpdateWebhookEndpoint
//
// Update a webhook endpoint.
//
// **Scopes**: `webhooks:write`
func (s *WebhooksService) UpdateWebhookEndpoint(ctx context.Context, id string, body WebhookEndpointUpdate) (*WebhookEndpoint, error) {
	var out WebhookEndpoint
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/webhooks/endpoints/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetWebhookEndpointSecret
//
// Regenerate a webhook endpoint secret.
//
// **Scopes**: `webhooks:write`
func (s *WebhooksService) ResetWebhookEndpointSecret(ctx context.Context, id string) (*WebhookEndpoint, error) {
	var out WebhookEndpoint
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/webhooks/endpoints/{id}/secret",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WebhooksListWebhookDeliveriesParams holds the query parameters of the request.
type WebhooksListWebhookDeliveriesParams struct {
	// EndpointID: Filter by webhook endpoint ID.
	EndpointID []string
	// StartTimestamp: Filter deliveries after this timestamp.
	StartTimestamp *string
	// EndTimestamp: Filter deliveries before this timestamp.
	EndTimestamp *string
	// Succeeded: Filter by delivery success status.
	Succeeded *bool
	// Query: Query to filter webhook deliveries.
	Query *string
	// HTTPCodeClass: Filter by HTTP response code class (2xx, 3xx, 4xx, 5xx).
	HTTPCodeClass *string
	// EventType: Filter by webhook event type.
	EventType []WebhookEventType
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p WebhooksListWebhookDeliveriesParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "endpoint_id", p.EndpointID)
	pago.AddQueryValue(query, "start_timestamp", p.StartTimestamp)
	pago.AddQueryValue(query, "end_timestamp", p.EndTimestamp)
	pago.AddQueryValue(query, "succeeded", p.Succeeded)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "http_code_class", p.HTTPCodeClass)
	pago.AddQueryValue(query, "event_type", p.EventType)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListWebhookDeliveries
//
// List webhook deliveries.
//
// Deliveries are all the attempts to deliver a webhook event to an endpoint.
//
// **Scopes**: `webhooks:read` `webhooks:write`
func (s *WebhooksService) ListWebhookDeliveries(ctx context.Context, params WebhooksListWebhookDeliveriesParams) (*ListResourceWebhookDelivery, error) {
	var out ListResourceWebhookDelivery
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/webhooks/deliveries",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWebhookDeliveriesAutoPaging returns an iterator over every page of
// ListWebhookDeliveries, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *WebhooksService) ListWebhookDeliveriesAutoPaging(ctx context.Context, params WebhooksListWebhookDeliveriesParams) iter.Seq2[WebhookDelivery, error] {
	return func(yield func(WebhookDelivery, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListWebhookDeliveries(ctx, pageParams)
			if err != nil {
				var zero WebhookDelivery
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// RedeliverWebhookEvent
//
// Schedule the re-delivery of a webhook event.
//
// **Scopes**: `webhooks:write`
func (s *WebhooksService) RedeliverWebhookEvent(ctx context.Context, id string) (any, error) {
	var out any
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/webhooks/events/{id}/redeliver",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
