// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// MetersService exposes the Meters endpoints.
type MetersService struct {
	client *pago.ClientBase
}

func newMetersService(client *pago.ClientBase) *MetersService {
	return &MetersService{
		client: client,
	}
}

// MetersListParams holds the query parameters of the request.
type MetersListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Query: Filter by name.
	Query *string
	// IsArchived: Filter on archived meters.
	IsArchived *bool
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['name']"
	Sorting []MeterSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p MetersListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "is_archived", p.IsArchived)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List meters.
//
// **Scopes**: `meters:read` `meters:write`
func (s *MetersService) List(ctx context.Context, params MetersListParams) (*ListResourceMeter, error) {
	var out ListResourceMeter
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/meters/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *MetersService) ListAutoPaging(ctx context.Context, params MetersListParams) iter.Seq2[Meter, error] {
	return func(yield func(Meter, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Meter
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a meter.
//
// **Scopes**: `meters:write`
func (s *MetersService) Create(ctx context.Context, body MeterCreate) (*Meter, error) {
	var out Meter
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/meters/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a meter by ID.
//
// **Scopes**: `meters:read` `meters:write`
func (s *MetersService) Get(ctx context.Context, id string) (*Meter, error) {
	var out Meter
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/meters/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update a meter.
//
// **Scopes**: `meters:write`
func (s *MetersService) Update(ctx context.Context, id string, body MeterUpdate) (*Meter, error) {
	var out Meter
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/meters/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MetersQuantitiesParams holds the query parameters of the request.
type MetersQuantitiesParams struct {
	// StartTimestamp: Start timestamp.
	StartTimestamp string
	// EndTimestamp: End timestamp.
	EndTimestamp string
	// Interval: Interval between two timestamps.
	Interval TimeInterval
	// Timezone: Timezone to use for the timestamps. Default is UTC.
	//
	// Default applied by the API: "UTC"
	Timezone *Timezone
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by external customer ID.
	ExternalCustomerID []string
	// CustomerAggregationFunction: If set, will first compute the quantities per customer before aggregating them using the given function. If not set, the quantities will be aggregated across all events.
	CustomerAggregationFunction *AggregationFunction
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p MetersQuantitiesParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "start_timestamp", p.StartTimestamp)
	pago.AddQueryValue(query, "end_timestamp", p.EndTimestamp)
	pago.AddQueryValue(query, "interval", p.Interval)
	pago.AddQueryValue(query, "timezone", p.Timezone)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "customer_aggregation_function", p.CustomerAggregationFunction)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// Quantities
//
// Get quantities of a meter over a time period.
//
// **Scopes**: `meters:read` `meters:write`
func (s *MetersService) Quantities(ctx context.Context, id string, params MetersQuantitiesParams) (*MeterQuantities, error) {
	var out MeterQuantities
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/meters/{id}/quantities",
		PathParams: map[string]any{
			"id": id,
		},
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
