// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// OrganizationsService exposes the Organizations endpoints.
type OrganizationsService struct {
	client *pago.ClientBase
}

func newOrganizationsService(client *pago.ClientBase) *OrganizationsService {
	return &OrganizationsService{
		client: client,
	}
}

// OrganizationsListParams holds the query parameters of the request.
type OrganizationsListParams struct {
	// Slug: Filter by slug.
	Slug *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['created_at']"
	Sorting []OrganizationSortProperty
}

func (p OrganizationsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "slug", p.Slug)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List organizations.
//
// **Scopes**: `organizations:read` `organizations:write`
func (s *OrganizationsService) List(ctx context.Context, params OrganizationsListParams) (*ListResourceOrganization, error) {
	var out ListResourceOrganization
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/organizations/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *OrganizationsService) ListAutoPaging(ctx context.Context, params OrganizationsListParams) iter.Seq2[Organization, error] {
	return func(yield func(Organization, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Organization
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create an organization.
//
// **Scopes**: `organizations:write`
func (s *OrganizationsService) Create(ctx context.Context, body OrganizationCreate) (*Organization, error) {
	var out Organization
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/organizations/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newCannotCreateOrganizationResponseError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get an organization by ID.
//
// **Scopes**: `organizations:read` `organizations:write`
func (s *OrganizationsService) Get(ctx context.Context, id string) (*Organization, error) {
	var out Organization
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/organizations/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update an organization.
//
// **Scopes**: `organizations:write`
func (s *OrganizationsService) Update(ctx context.Context, id string, body OrganizationUpdate) (*Organization, error) {
	var out Organization
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/organizations/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			409: newSsoEnforcementRequiresConnectionError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
