// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// MetricsService exposes the Metrics endpoints.
type MetricsService struct {
	client *pago.ClientBase
}

func newMetricsService(client *pago.ClientBase) *MetricsService {
	return &MetricsService{
		client: client,
	}
}

// MetricsGetParams holds the query parameters of the request.
type MetricsGetParams struct {
	// StartDate: Start date.
	StartDate string
	// EndDate: End date.
	EndDate string
	// Timezone: Timezone to use for the timestamps. Default is UTC.
	//
	// Default applied by the API: "UTC"
	Timezone *Timezone
	// Interval: Interval between two timestamps.
	Interval TimeInterval
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
	// BillingType: Filter by billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
	BillingType []ProductBillingType
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// Metrics: List of metric slugs to focus on. When provided, only the queries needed for these metrics will be executed, improving performance. If not provided, all metrics are returned.
	Metrics []string
}

func (p MetricsGetParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "start_date", p.StartDate)
	pago.AddQueryValue(query, "end_date", p.EndDate)
	pago.AddQueryValue(query, "timezone", p.Timezone)
	pago.AddQueryValue(query, "interval", p.Interval)
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "billing_type", p.BillingType)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "metrics", p.Metrics)
	return query
}

// Get
//
// Get metrics about your orders and subscriptions.
//
// Currency values are output in cents.
//
// **Scopes**: `metrics:read`
func (s *MetricsService) Get(ctx context.Context, params MetricsGetParams) (*MetricsResponse, error) {
	var out MetricsResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/metrics/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MetricsExportParams holds the query parameters of the request.
type MetricsExportParams struct {
	// StartDate: Start date.
	StartDate string
	// EndDate: End date.
	EndDate string
	// Timezone: Timezone to use for the timestamps. Default is UTC.
	//
	// Default applied by the API: "UTC"
	Timezone *Timezone
	// Interval: Interval between two timestamps.
	Interval TimeInterval
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
	// BillingType: Filter by billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
	BillingType []ProductBillingType
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// Metrics: List of metric slugs to include in the export. If not provided, all metrics are exported.
	Metrics []string
}

func (p MetricsExportParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "start_date", p.StartDate)
	pago.AddQueryValue(query, "end_date", p.EndDate)
	pago.AddQueryValue(query, "timezone", p.Timezone)
	pago.AddQueryValue(query, "interval", p.Interval)
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "billing_type", p.BillingType)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "metrics", p.Metrics)
	return query
}

// Export
//
// Export metrics as a CSV file.
//
// **Scopes**: `metrics:read`
func (s *MetricsService) Export(ctx context.Context, params MetricsExportParams) (string, error) {
	var out string
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/metrics/export",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseText,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return "", err
	}
	return out, nil
}

// Limits
//
// Get the interval limits for the metrics endpoint.
//
// **Scopes**: `metrics:read`
func (s *MetricsService) Limits(ctx context.Context) (*MetricsLimits, error) {
	var out MetricsLimits
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/metrics/limits",
		ResponseType: pago.ResponseJSON,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MetricsListDashboardsParams holds the query parameters of the request.
type MetricsListDashboardsParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
}

func (p MetricsListDashboardsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	return query
}

// ListDashboards
//
// List user-defined metric dashboards.
//
// **Scopes**: `metrics:read`
func (s *MetricsService) ListDashboards(ctx context.Context, params MetricsListDashboardsParams) ([]MetricDashboardSchema, error) {
	var out []MetricDashboardSchema
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/metrics/dashboards",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateDashboard
//
// Create a user-defined metric dashboard.
//
// **Scopes**: `metrics:write`
func (s *MetricsService) CreateDashboard(ctx context.Context, body MetricDashboardCreate) (*MetricDashboardSchema, error) {
	var out MetricDashboardSchema
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/metrics/dashboards",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDashboard
//
// Get a user-defined metric dashboard by ID.
//
// **Scopes**: `metrics:read`
func (s *MetricsService) GetDashboard(ctx context.Context, id string) (*MetricDashboardSchema, error) {
	var out MetricDashboardSchema
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/metrics/dashboards/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteDashboard
//
// Delete a user-defined metric dashboard.
//
// **Scopes**: `metrics:write`
func (s *MetricsService) DeleteDashboard(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/metrics/dashboards/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// UpdateDashboard
//
// Update a user-defined metric dashboard.
//
// **Scopes**: `metrics:write`
func (s *MetricsService) UpdateDashboard(ctx context.Context, id string, body MetricDashboardUpdate) (*MetricDashboardSchema, error) {
	var out MetricDashboardSchema
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/metrics/dashboards/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
