// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CheckoutLinksService exposes the CheckoutLinks endpoints.
type CheckoutLinksService struct {
	client *pago.ClientBase
}

func newCheckoutLinksService(client *pago.ClientBase) *CheckoutLinksService {
	return &CheckoutLinksService{
		client: client,
	}
}

// CheckoutLinksListParams holds the query parameters of the request.
type CheckoutLinksListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['created_at']"
	Sorting []CheckoutLinkSortProperty
}

func (p CheckoutLinksListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List checkout links.
//
// **Scopes**: `checkout_links:read` `checkout_links:write`
func (s *CheckoutLinksService) List(ctx context.Context, params CheckoutLinksListParams) (*ListResourceCheckoutLink, error) {
	var out ListResourceCheckoutLink
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/checkout-links/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CheckoutLinksService) ListAutoPaging(ctx context.Context, params CheckoutLinksListParams) iter.Seq2[CheckoutLink, error] {
	return func(yield func(CheckoutLink, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CheckoutLink
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a checkout link.
//
// **Scopes**: `checkout_links:write`
func (s *CheckoutLinksService) Create(ctx context.Context, body CheckoutLinkCreate) (*CheckoutLink, error) {
	var out CheckoutLink
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/checkout-links/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a checkout link by ID.
//
// **Scopes**: `checkout_links:read` `checkout_links:write`
func (s *CheckoutLinksService) Get(ctx context.Context, id string) (*CheckoutLink, error) {
	var out CheckoutLink
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/checkout-links/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete
//
// Delete a checkout link.
//
// **Scopes**: `checkout_links:write`
func (s *CheckoutLinksService) Delete(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/checkout-links/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a checkout link.
//
// **Scopes**: `checkout_links:write`
func (s *CheckoutLinksService) Update(ctx context.Context, id string, body CheckoutLinkUpdate) (*CheckoutLink, error) {
	var out CheckoutLink
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/checkout-links/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
