// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"

	pago "github.com/pago-sh/pago-go"
)

// CustomerSessionsService exposes the CustomerSessions endpoints.
type CustomerSessionsService struct {
	client *pago.ClientBase
}

func newCustomerSessionsService(client *pago.ClientBase) *CustomerSessionsService {
	return &CustomerSessionsService{
		client: client,
	}
}

// Create
//
// Create a customer session.
//
// For organizations with `member_model_enabled`, this will automatically
// create a member session for the owner member of the customer.
//
// **Scopes**: `customer_sessions:write`
func (s *CustomerSessionsService) Create(ctx context.Context, body CustomerSessionCustomerIDCreateUnion) (*CustomerSession, error) {
	var out CustomerSession
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customer-sessions/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
