// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// BenefitsService exposes the Benefits endpoints.
type BenefitsService struct {
	client *pago.ClientBase
}

func newBenefitsService(client *pago.ClientBase) *BenefitsService {
	return &BenefitsService{
		client: client,
	}
}

// BenefitsListParams holds the query parameters of the request.
type BenefitsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Type: Filter by benefit type.
	Type []BenefitType
	// ID: Filter by benefit IDs.
	ID []string
	// ExcludeID: Exclude benefits with these IDs.
	ExcludeID []string
	// Query: Filter by description.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []BenefitSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p BenefitsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "type", p.Type)
	pago.AddQueryValue(query, "id", p.ID)
	pago.AddQueryValue(query, "exclude_id", p.ExcludeID)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List benefits.
//
// **Scopes**: `benefits:read` `benefits:write`
func (s *BenefitsService) List(ctx context.Context, params BenefitsListParams) (*ListResourceBenefit, error) {
	var out ListResourceBenefit
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/benefits/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *BenefitsService) ListAutoPaging(ctx context.Context, params BenefitsListParams) iter.Seq2[Benefit, error] {
	return func(yield func(Benefit, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Benefit
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a benefit.
//
// **Scopes**: `benefits:write`
func (s *BenefitsService) Create(ctx context.Context, body BenefitCreate) (*Benefit, error) {
	var out Benefit
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/benefits/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a benefit by ID.
//
// **Scopes**: `benefits:read` `benefits:write`
func (s *BenefitsService) Get(ctx context.Context, id string) (*Benefit, error) {
	var out Benefit
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/benefits/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete
//
// Delete a benefit.
//
// > [!WARNING]
// > Every grants associated with the benefit will be revoked.
// > Users will lose access to the benefit.
//
// **Scopes**: `benefits:write`
func (s *BenefitsService) Delete(ctx context.Context, id string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/benefits/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a benefit.
//
// **Scopes**: `benefits:write`
func (s *BenefitsService) Update(ctx context.Context, id string, body BenefitUpdateUnion) (*Benefit, error) {
	var out Benefit
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/benefits/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BenefitsGrantsParams holds the query parameters of the request.
type BenefitsGrantsParams struct {
	// IsGranted: Filter by granted status. If `true`, only granted benefits will be returned. If `false`, only revoked benefits will be returned.
	IsGranted *bool
	// CustomerID: Filter by customer.
	CustomerID []string
	// MemberID: Filter by member.
	MemberID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p BenefitsGrantsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "is_granted", p.IsGranted)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "member_id", p.MemberID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// Grants
//
// List the individual grants for a benefit.
//
// It's especially useful to check if a user has been granted a benefit.
//
// **Scopes**: `benefits:read` `benefits:write`
func (s *BenefitsService) Grants(ctx context.Context, id string, params BenefitsGrantsParams) (*ListResourceBenefitGrant, error) {
	var out ListResourceBenefitGrant
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/benefits/{id}/grants",
		PathParams: map[string]any{
			"id": id,
		},
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GrantsAutoPaging returns an iterator over every page of
// Grants, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *BenefitsService) GrantsAutoPaging(ctx context.Context, id string, params BenefitsGrantsParams) iter.Seq2[BenefitGrant, error] {
	return func(yield func(BenefitGrant, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.Grants(ctx, id, pageParams)
			if err != nil {
				var zero BenefitGrant
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}
