// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// LicenseKeysService exposes the LicenseKeys endpoints.
type LicenseKeysService struct {
	client *pago.ClientBase
}

func newLicenseKeysService(client *pago.ClientBase) *LicenseKeysService {
	return &LicenseKeysService{
		client: client,
	}
}

// LicenseKeysListParams holds the query parameters of the request.
type LicenseKeysListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// BenefitID: Filter by benefit ID.
	BenefitID []string
	// Status: Filter by license key status.
	Status []LicenseKeyStatus
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p LicenseKeysListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "benefit_id", p.BenefitID)
	pago.AddQueryValue(query, "status", p.Status)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// List
//
// Get license keys connected to the given organization & filters.
//
// **Scopes**: `license_keys:read` `license_keys:write`
func (s *LicenseKeysService) List(ctx context.Context, params LicenseKeysListParams) (*ListResourceLicenseKeyRead, error) {
	var out ListResourceLicenseKeyRead
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/license-keys/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newUnauthorizedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *LicenseKeysService) ListAutoPaging(ctx context.Context, params LicenseKeysListParams) iter.Seq2[LicenseKeyRead, error] {
	return func(yield func(LicenseKeyRead, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero LicenseKeyRead
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a license key.
//
// **Scopes**: `license_keys:read` `license_keys:write`
func (s *LicenseKeysService) Get(ctx context.Context, id string) (*LicenseKeyWithActivations, error) {
	var out LicenseKeyWithActivations
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/license-keys/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newUnauthorizedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update a license key.
//
// **Scopes**: `license_keys:write`
func (s *LicenseKeysService) Update(ctx context.Context, id string, body LicenseKeyUpdate) (*LicenseKeyRead, error) {
	var out LicenseKeyRead
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/license-keys/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newUnauthorizedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetActivation
//
// Get a license key activation.
//
// **Scopes**: `license_keys:read` `license_keys:write`
func (s *LicenseKeysService) GetActivation(ctx context.Context, id string, activationID string) (*LicenseKeyActivationRead, error) {
	var out LicenseKeyActivationRead
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/license-keys/{id}/activations/{activation_id}",
		PathParams: map[string]any{
			"id":            id,
			"activation_id": activationID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			401: newUnauthorizedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Validate
//
// Validate a license key.
//
// **Scopes**: `license_keys:write`
func (s *LicenseKeysService) Validate(ctx context.Context, body LicenseKeyValidate) (*ValidatedLicenseKey, error) {
	var out ValidatedLicenseKey
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/license-keys/validate",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Activate
//
// Activate a license key instance.
//
// **Scopes**: `license_keys:write`
func (s *LicenseKeysService) Activate(ctx context.Context, body LicenseKeyActivate) (*LicenseKeyActivationRead, error) {
	var out LicenseKeyActivationRead
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/license-keys/activate",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Deactivate
//
// Deactivate a license key instance.
//
// **Scopes**: `license_keys:write`
func (s *LicenseKeysService) Deactivate(ctx context.Context, body LicenseKeyDeactivate) error {
	return s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/license-keys/deactivate",
		Body:         body,
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}
