// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// BenefitGrantsService exposes the BenefitGrants endpoints.
type BenefitGrantsService struct {
	client *pago.ClientBase
}

func newBenefitGrantsService(client *pago.ClientBase) *BenefitGrantsService {
	return &BenefitGrantsService{
		client: client,
	}
}

// BenefitGrantsListParams holds the query parameters of the request.
type BenefitGrantsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by customer external ID.
	ExternalCustomerID []string
	// IsGranted: Filter by granted status. If `true`, only granted benefits will be returned. If `false`, only revoked benefits will be returned.
	IsGranted *bool
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []BenefitGrantSortProperty
}

func (p BenefitGrantsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "is_granted", p.IsGranted)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List benefit grants across all benefits accessible to the authenticated subject.
//
// **Scopes**: `benefits:read` `benefits:write`
func (s *BenefitGrantsService) List(ctx context.Context, params BenefitGrantsListParams) (*ListResourceBenefitGrant, error) {
	var out ListResourceBenefitGrant
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/benefit-grants/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *BenefitGrantsService) ListAutoPaging(ctx context.Context, params BenefitGrantsListParams) iter.Seq2[BenefitGrant, error] {
	return func(yield func(BenefitGrant, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero BenefitGrant
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}
