// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// SubscriptionsService exposes the Subscriptions endpoints.
type SubscriptionsService struct {
	client *pago.ClientBase
}

func newSubscriptionsService(client *pago.ClientBase) *SubscriptionsService {
	return &SubscriptionsService{
		client: client,
	}
}

// SubscriptionsListParams holds the query parameters of the request.
type SubscriptionsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// ProductID: Filter by product ID.
	ProductID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by customer external ID.
	ExternalCustomerID []string
	// DiscountID: Filter by discount ID.
	DiscountID []string
	// Active: Filter by active or inactive subscription.
	//
	// Deprecated: this parameter is deprecated.
	Active *bool
	// Status: Filter by subscription status.
	Status []SubscriptionStatus
	// CancelAtPeriodEnd: Filter by subscriptions that are set to cancel at period end.
	CancelAtPeriodEnd *bool
	// CustomerCancellationReason: Filter by customer cancellation reason.
	CustomerCancellationReason []CustomerCancellationReason
	// CanceledAtAfter: Filter by cancellation date (after or equal to).
	CanceledAtAfter *string
	// CanceledAtBefore: Filter by cancellation date (before or equal to).
	CanceledAtBefore *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-started_at']"
	Sorting []SubscriptionSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p SubscriptionsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "product_id", p.ProductID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "discount_id", p.DiscountID)
	pago.AddQueryValue(query, "active", p.Active)
	pago.AddQueryValue(query, "status", p.Status)
	pago.AddQueryValue(query, "cancel_at_period_end", p.CancelAtPeriodEnd)
	pago.AddQueryValue(query, "customer_cancellation_reason", p.CustomerCancellationReason)
	pago.AddQueryValue(query, "canceled_at_after", p.CanceledAtAfter)
	pago.AddQueryValue(query, "canceled_at_before", p.CanceledAtBefore)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List subscriptions.
//
// **Scopes**: `subscriptions:read` `subscriptions:write`
func (s *SubscriptionsService) List(ctx context.Context, params SubscriptionsListParams) (*ListResourceSubscription, error) {
	var out ListResourceSubscription
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/subscriptions/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *SubscriptionsService) ListAutoPaging(ctx context.Context, params SubscriptionsListParams) iter.Seq2[Subscription, error] {
	return func(yield func(Subscription, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Subscription
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a subscription programmatically.
//
// This endpoint only allows to create subscription on free products.
// For paid products, use the checkout flow.
//
// No initial order will be created and no confirmation email will be sent.
//
// **Scopes**: `subscriptions:write`
func (s *SubscriptionsService) Create(ctx context.Context, body SubscriptionCreateCustomerUnion) (*Subscription, error) {
	var out Subscription
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/subscriptions/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubscriptionsExportParams holds the query parameters of the request.
type SubscriptionsExportParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
}

func (p SubscriptionsExportParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	return query
}

// Export
//
// Export subscriptions as a CSV file.
//
// **Scopes**: `subscriptions:read` `subscriptions:write`
func (s *SubscriptionsService) Export(ctx context.Context, params SubscriptionsExportParams) (string, error) {
	var out string
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/subscriptions/export",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseText,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return "", err
	}
	return out, nil
}

// Get
//
// Get a subscription by ID.
//
// **Scopes**: `subscriptions:read` `subscriptions:write`
func (s *SubscriptionsService) Get(ctx context.Context, id string) (*Subscription, error) {
	var out Subscription
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/subscriptions/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Revoke
//
// Revoke a subscription, i.e cancel immediately.
//
// **Scopes**: `subscriptions:write`
func (s *SubscriptionsService) Revoke(ctx context.Context, id string) (*Subscription, error) {
	var out Subscription
	err := s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/subscriptions/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newAlreadyCanceledSubscriptionError,
			404: newResourceNotFoundError,
			409: newSubscriptionLockedError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update
//
// Update a subscription.
//
// **Scopes**: `subscriptions:write`
func (s *SubscriptionsService) Update(ctx context.Context, id string, body SubscriptionUpdate) (*Subscription, error) {
	var out Subscription
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/subscriptions/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			402: newPaymentFailedError,
			403: newAlreadyCanceledSubscriptionError,
			404: newResourceNotFoundError,
			409: newSubscriptionLockedError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
