// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CustomerMetersService exposes the CustomerMeters endpoints.
type CustomerMetersService struct {
	client *pago.ClientBase
}

func newCustomerMetersService(client *pago.ClientBase) *CustomerMetersService {
	return &CustomerMetersService{
		client: client,
	}
}

// CustomerMetersListParams holds the query parameters of the request.
type CustomerMetersListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by external customer ID.
	ExternalCustomerID []string
	// MeterID: Filter by meter ID.
	MeterID []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-modified_at']"
	Sorting []CustomerMeterSortProperty
}

func (p CustomerMetersListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "meter_id", p.MeterID)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List customer meters.
//
// **Scopes**: `customer_meters:read`
func (s *CustomerMetersService) List(ctx context.Context, params CustomerMetersListParams) (*ListResourceCustomerMeter, error) {
	var out ListResourceCustomerMeter
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customer-meters/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomerMetersService) ListAutoPaging(ctx context.Context, params CustomerMetersListParams) iter.Seq2[CustomerMeter, error] {
	return func(yield func(CustomerMeter, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero CustomerMeter
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a customer meter by ID.
//
// **Scopes**: `customer_meters:read`
func (s *CustomerMetersService) Get(ctx context.Context, id string) (*CustomerMeter, error) {
	var out CustomerMeter
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customer-meters/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
