// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// CustomersService exposes the Customers endpoints.
type CustomersService struct {
	client *pago.ClientBase

	// Members exposes the Members endpoints.
	Members *CustomersMembersService
}

func newCustomersService(client *pago.ClientBase) *CustomersService {
	return &CustomersService{
		client:  client,
		Members: newCustomersMembersService(client),
	}
}

// CustomersListParams holds the query parameters of the request.
type CustomersListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// Email: Filter by exact email.
	Email *string
	// Query: Filter by name, email, or external ID.
	Query *string
	// Active: Filter by active customers, i.e. customers with at least one trialing, active or past_due subscription.
	Active *bool
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []CustomerSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p CustomersListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "email", p.Email)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "active", p.Active)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List customers.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) List(ctx context.Context, params CustomersListParams) (*ListResourceCustomer, error) {
	var out ListResourceCustomer
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customers/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomersService) ListAutoPaging(ctx context.Context, params CustomersListParams) iter.Seq2[Customer, error] {
	return func(yield func(Customer, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Customer
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Create
//
// Create a customer.
//
// **Scopes**: `customers:write`
func (s *CustomersService) Create(ctx context.Context, body CustomerCreate) (*Customer, error) {
	var out Customer
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/customers/",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomersExportParams holds the query parameters of the request.
type CustomersExportParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
}

func (p CustomersExportParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	return query
}

// Export
//
// Export customers as a CSV file.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) Export(ctx context.Context, params CustomersExportParams) (string, error) {
	var out string
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/customers/export",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseText,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return "", err
	}
	return out, nil
}

// Get
//
// Get a customer by ID.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) Get(ctx context.Context, id string) (*Customer, error) {
	var out Customer
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomersDeleteParams holds the query parameters of the request.
type CustomersDeleteParams struct {
	// Anonymize: If true, also anonymize the customer's personal data for GDPR compliance. This replaces email with a hashed version, hashes name and billing name (name preserved for businesses with tax_id), clears billing address, and removes OAuth account data.
	//
	// Default applied by the API: false
	Anonymize *bool
}

func (p CustomersDeleteParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "anonymize", p.Anonymize)
	return query
}

// Delete
//
// Delete a customer.
//
// This action cannot be undone and will immediately:
// - Cancel any active subscriptions for the customer
// - Revoke all their benefits
// - Clear any `external_id`
//
// Use it only in the context of deleting a user within your
// own service. Otherwise, use more granular API endpoints to cancel
// a specific subscription or revoke certain benefits.
//
// Note: The customers information will nonetheless be retained for historic
// orders and subscriptions.
//
// Set `anonymize=true` to also anonymize PII for GDPR compliance.
//
// **Scopes**: `customers:write`
func (s *CustomersService) Delete(ctx context.Context, id string, params CustomersDeleteParams) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customers/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Query:        params.queryValues(),
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a customer.
//
// **Scopes**: `customers:write`
func (s *CustomersService) Update(ctx context.Context, id string, body CustomerUpdate) (*Customer, error) {
	var out Customer
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customers/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExternal
//
// Get a customer by external ID.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) GetExternal(ctx context.Context, externalID string) (*Customer, error) {
	var out Customer
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/external/{external_id}",
		PathParams: map[string]any{
			"external_id": externalID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomersDeleteExternalParams holds the query parameters of the request.
type CustomersDeleteExternalParams struct {
	// Anonymize: If true, also anonymize the customer's personal data for GDPR compliance.
	//
	// Default applied by the API: false
	Anonymize *bool
}

func (p CustomersDeleteExternalParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "anonymize", p.Anonymize)
	return query
}

// DeleteExternal
//
// Delete a customer by external ID.
//
// Immediately cancels any active subscriptions and revokes any active benefits.
//
// Set `anonymize=true` to also anonymize PII for GDPR compliance.
//
// **Scopes**: `customers:write`
func (s *CustomersService) DeleteExternal(ctx context.Context, externalID string, params CustomersDeleteExternalParams) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customers/external/{external_id}",
		PathParams: map[string]any{
			"external_id": externalID,
		},
		Query:        params.queryValues(),
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// UpdateExternal
//
// Update a customer by external ID.
//
// **Scopes**: `customers:write`
func (s *CustomersService) UpdateExternal(ctx context.Context, externalID string, body CustomerUpdateExternalID) (*Customer, error) {
	var out Customer
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customers/external/{external_id}",
		PathParams: map[string]any{
			"external_id": externalID,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetState
//
// Get a customer state by ID.
//
// The customer state includes information about
// the customer's active subscriptions and benefits.
//
// It's the ideal endpoint to use when you need to get a full overview
// of a customer's status.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) GetState(ctx context.Context, id string) (*CustomerState, error) {
	var out CustomerState
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/{id}/state",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStateExternal
//
// Get a customer state by external ID.
//
// The customer state includes information about
// the customer's active subscriptions and benefits.
//
// It's the ideal endpoint to use when you need to get a full overview
// of a customer's status.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) GetStateExternal(ctx context.Context, externalID string) (*CustomerState, error) {
	var out CustomerState
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/external/{external_id}/state",
		PathParams: map[string]any{
			"external_id": externalID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomersListPaymentMethodsParams holds the query parameters of the request.
type CustomersListPaymentMethodsParams struct {
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomersListPaymentMethodsParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListPaymentMethods
//
// Get saved payment methods of a customer.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) ListPaymentMethods(ctx context.Context, id string, params CustomersListPaymentMethodsParams) (*ListResourcePaymentMethod, error) {
	var out ListResourcePaymentMethod
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/{id}/payment-methods",
		PathParams: map[string]any{
			"id": id,
		},
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPaymentMethodsAutoPaging returns an iterator over every page of
// ListPaymentMethods, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomersService) ListPaymentMethodsAutoPaging(ctx context.Context, id string, params CustomersListPaymentMethodsParams) iter.Seq2[PaymentMethod, error] {
	return func(yield func(PaymentMethod, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListPaymentMethods(ctx, id, pageParams)
			if err != nil {
				var zero PaymentMethod
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// CustomersListPaymentMethodsExternalParams holds the query parameters of the request.
type CustomersListPaymentMethodsExternalParams struct {
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
}

func (p CustomersListPaymentMethodsExternalParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	return query
}

// ListPaymentMethodsExternal
//
// Get saved payment methods of a customer by external ID.
//
// **Scopes**: `customers:read` `customers:write`
func (s *CustomersService) ListPaymentMethodsExternal(ctx context.Context, externalID string, params CustomersListPaymentMethodsExternalParams) (*ListResourcePaymentMethod, error) {
	var out ListResourcePaymentMethod
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/external/{external_id}/payment-methods",
		PathParams: map[string]any{
			"external_id": externalID,
		},
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPaymentMethodsExternalAutoPaging returns an iterator over every page of
// ListPaymentMethodsExternal, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *CustomersService) ListPaymentMethodsExternalAutoPaging(ctx context.Context, externalID string, params CustomersListPaymentMethodsExternalParams) iter.Seq2[PaymentMethod, error] {
	return func(yield func(PaymentMethod, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListPaymentMethodsExternal(ctx, externalID, pageParams)
			if err != nil {
				var zero PaymentMethod
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// CustomersMembersService exposes the Customers.Members endpoints.
type CustomersMembersService struct {
	client *pago.ClientBase
}

func newCustomersMembersService(client *pago.ClientBase) *CustomersMembersService {
	return &CustomersMembersService{
		client: client,
	}
}

// Create
//
// Create a new member for a customer.
//
// Only B2B customers with the member management feature enabled can add members.
// The authenticated user or organization must have access to the customer's organization.
//
// **Scopes**: `members:write`
func (s *CustomersMembersService) Create(ctx context.Context, id string, body MemberCreateFromCustomer) (*Member, error) {
	var out Member
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/customers/{id}/members",
		PathParams: map[string]any{
			"id": id,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateExternal
//
// Create a new member for a customer identified by its external ID.
//
// **Scopes**: `members:write`
func (s *CustomersMembersService) CreateExternal(ctx context.Context, externalIDPath string, body MemberCreateFromCustomer) (*Member, error) {
	var out Member
	err := s.client.Do(ctx, pago.Request{
		Method: "POST",
		Path:   "/v1/customers/external/{external_id}/members",
		PathParams: map[string]any{
			"external_id": externalIDPath,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			403: newNotPermittedError,
			404: newResourceNotFoundError,
			409: newAmbiguousExternalCustomerIDError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get
//
// Get a member of a customer by its ID.
//
// **Scopes**: `members:read` `members:write`
func (s *CustomersMembersService) Get(ctx context.Context, id string, memberID string) (*Member, error) {
	var out Member
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/{id}/members/{member_id}",
		PathParams: map[string]any{
			"id":        id,
			"member_id": memberID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete
//
// Delete a member of a customer.
//
// **Scopes**: `members:write`
func (s *CustomersMembersService) Delete(ctx context.Context, id string, memberID string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customers/{id}/members/{member_id}",
		PathParams: map[string]any{
			"id":        id,
			"member_id": memberID,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// Update
//
// Update a member of a customer.
//
// Only name, email and role can be updated.
//
// **Scopes**: `members:write`
func (s *CustomersMembersService) Update(ctx context.Context, id string, memberID string, body MemberUpdate) (*Member, error) {
	var out Member
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customers/{id}/members/{member_id}",
		PathParams: map[string]any{
			"id":        id,
			"member_id": memberID,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExternal
//
// Get a member by external ID for a customer identified by its external ID.
//
// **Scopes**: `members:read` `members:write`
func (s *CustomersMembersService) GetExternal(ctx context.Context, externalID string, memberExternalID string) (*Member, error) {
	var out Member
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/customers/external/{external_id}/members/{member_external_id}",
		PathParams: map[string]any{
			"external_id":        externalID,
			"member_external_id": memberExternalID,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newAmbiguousExternalCustomerIDError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteExternal
//
// Delete a member by external ID for a customer identified by its external ID.
//
// **Scopes**: `members:write`
func (s *CustomersMembersService) DeleteExternal(ctx context.Context, externalID string, memberExternalID string) error {
	return s.client.Do(ctx, pago.Request{
		Method: "DELETE",
		Path:   "/v1/customers/external/{external_id}/members/{member_external_id}",
		PathParams: map[string]any{
			"external_id":        externalID,
			"member_external_id": memberExternalID,
		},
		ResponseType: pago.ResponseNone,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newAmbiguousExternalCustomerIDError,
			422: newHTTPValidationResponseError,
		},
	}, nil)
}

// UpdateExternal
//
// Update a member by external ID for a customer identified by its external ID.
//
// **Scopes**: `members:write`
func (s *CustomersMembersService) UpdateExternal(ctx context.Context, externalID string, memberExternalID string, body MemberUpdate) (*Member, error) {
	var out Member
	err := s.client.Do(ctx, pago.Request{
		Method: "PATCH",
		Path:   "/v1/customers/external/{external_id}/members/{member_external_id}",
		PathParams: map[string]any{
			"external_id":        externalID,
			"member_external_id": memberExternalID,
		},
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			409: newAmbiguousExternalCustomerIDError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
