// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// EventsService exposes the Events endpoints.
type EventsService struct {
	client *pago.ClientBase
}

func newEventsService(client *pago.ClientBase) *EventsService {
	return &EventsService{
		client: client,
	}
}

// EventsListParams holds the query parameters of the request.
type EventsListParams struct {
	// Filter: Filter events following filter clauses. JSON string following the same schema a meter filter clause.
	Filter *string
	// StartTimestamp: Filter events after this timestamp.
	StartTimestamp *string
	// EndTimestamp: Filter events before this timestamp.
	EndTimestamp *string
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by external customer ID.
	ExternalCustomerID []string
	// MeterID: Filter by a meter filter clause.
	MeterID *string
	// Name: Filter by event name.
	Name []string
	// Source: Filter by event source.
	Source []EventSource
	// Query: Query to filter events.
	Query *string
	// ParentID: When combined with depth, use this event as the anchor instead of root events.
	ParentID *string
	// Depth: Fetch descendants up to this depth. When set: 0=root events only, 1=roots+children, etc. Max 5. When not set, returns all events.
	Depth *int
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-timestamp']"
	Sorting []EventSortProperty
	// Metadata: Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
	Metadata *MetadataQuery
}

func (p EventsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "filter", p.Filter)
	pago.AddQueryValue(query, "start_timestamp", p.StartTimestamp)
	pago.AddQueryValue(query, "end_timestamp", p.EndTimestamp)
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "meter_id", p.MeterID)
	pago.AddQueryValue(query, "name", p.Name)
	pago.AddQueryValue(query, "source", p.Source)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "parent_id", p.ParentID)
	pago.AddQueryValue(query, "depth", p.Depth)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	pago.AddQueryValue(query, "metadata", p.Metadata)
	return query
}

// List
//
// List events.
//
// **Scopes**: `events:read` `events:write`
func (s *EventsService) List(ctx context.Context, params EventsListParams) (*ListResourceEventUnion, error) {
	var out ListResourceEventUnion
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/events/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EventsListNamesParams holds the query parameters of the request.
type EventsListNamesParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// ExternalCustomerID: Filter by external customer ID.
	ExternalCustomerID []string
	// Source: Filter by event source.
	Source []EventSource
	// Query: Query to filter event names.
	Query *string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-last_seen']"
	Sorting []EventNamesSortProperty
}

func (p EventsListNamesParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "external_customer_id", p.ExternalCustomerID)
	pago.AddQueryValue(query, "source", p.Source)
	pago.AddQueryValue(query, "query", p.Query)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// ListNames
//
// List event names.
//
// **Scopes**: `events:read` `events:write`
func (s *EventsService) ListNames(ctx context.Context, params EventsListNamesParams) (*ListResourceEventName, error) {
	var out ListResourceEventName
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/events/names",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNamesAutoPaging returns an iterator over every page of
// ListNames, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *EventsService) ListNamesAutoPaging(ctx context.Context, params EventsListNamesParams) iter.Seq2[EventName, error] {
	return func(yield func(EventName, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.ListNames(ctx, pageParams)
			if err != nil {
				var zero EventName
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get an event by ID.
//
// **Scopes**: `events:read` `events:write`
func (s *EventsService) Get(ctx context.Context, id string) (*Event, error) {
	var out Event
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/events/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Ingest
//
// Ingest batch of events.
//
// **Scopes**: `events:write`
func (s *EventsService) Ingest(ctx context.Context, body EventsIngest) (*EventsIngestResponse, error) {
	var out EventsIngestResponse
	err := s.client.Do(ctx, pago.Request{
		Method:       "POST",
		Path:         "/v1/events/ingest",
		Body:         body,
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
