// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"context"
	"iter"
	"net/url"

	pago "github.com/pago-sh/pago-go"
)

// PaymentsService exposes the Payments endpoints.
type PaymentsService struct {
	client *pago.ClientBase
}

func newPaymentsService(client *pago.ClientBase) *PaymentsService {
	return &PaymentsService{
		client: client,
	}
}

// PaymentsListParams holds the query parameters of the request.
type PaymentsListParams struct {
	// OrganizationID: Filter by organization ID.
	OrganizationID []string
	// CheckoutID: Filter by checkout ID.
	CheckoutID []string
	// OrderID: Filter by order ID.
	OrderID []string
	// CustomerID: Filter by customer ID.
	CustomerID []string
	// Status: Filter by payment status.
	Status []PaymentStatus
	// Method: Filter by payment method.
	Method []string
	// CustomerEmail: Filter by customer email.
	CustomerEmail []string
	// Page: Page number, defaults to 1.
	//
	// Default applied by the API: 1
	Page *int
	// Limit: Size of a page, defaults to 10. Maximum is 100.
	//
	// Default applied by the API: 10
	Limit *int
	// Sorting: Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	//
	// Default applied by the API: "['-created_at']"
	Sorting []PaymentSortProperty
}

func (p PaymentsListParams) queryValues() url.Values {
	query := url.Values{}
	pago.AddQueryValue(query, "organization_id", p.OrganizationID)
	pago.AddQueryValue(query, "checkout_id", p.CheckoutID)
	pago.AddQueryValue(query, "order_id", p.OrderID)
	pago.AddQueryValue(query, "customer_id", p.CustomerID)
	pago.AddQueryValue(query, "status", p.Status)
	pago.AddQueryValue(query, "method", p.Method)
	pago.AddQueryValue(query, "customer_email", p.CustomerEmail)
	pago.AddQueryValue(query, "page", p.Page)
	pago.AddQueryValue(query, "limit", p.Limit)
	pago.AddQueryValue(query, "sorting", p.Sorting)
	return query
}

// List
//
// List payments.
//
// **Scopes**: `payments:read`
func (s *PaymentsService) List(ctx context.Context, params PaymentsListParams) (*ListResourcePayment, error) {
	var out ListResourcePayment
	err := s.client.Do(ctx, pago.Request{
		Method:       "GET",
		Path:         "/v1/payments/",
		Query:        params.queryValues(),
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAutoPaging returns an iterator over every page of
// List, fetching the next page as it is consumed.
//
// Iteration stops at the first error, which is yielded with the zero value of
// the item.
func (s *PaymentsService) ListAutoPaging(ctx context.Context, params PaymentsListParams) iter.Seq2[Payment, error] {
	return func(yield func(Payment, error) bool) {
		page := 1
		if params.Page != nil {
			page = *params.Page
		}
		for {
			pageParams := params
			currentPage := page
			pageParams.Page = &currentPage

			response, err := s.List(ctx, pageParams)
			if err != nil {
				var zero Payment
				yield(zero, err)
				return
			}
			for _, item := range response.Items {
				if !yield(item, nil) {
					return
				}
			}
			if page >= response.Pagination.MaxPage {
				return
			}
			page++
		}
	}
}

// Get
//
// Get a payment by ID.
//
// **Scopes**: `payments:read`
func (s *PaymentsService) Get(ctx context.Context, id string) (*Payment, error) {
	var out Payment
	err := s.client.Do(ctx, pago.Request{
		Method: "GET",
		Path:   "/v1/payments/{id}",
		PathParams: map[string]any{
			"id": id,
		},
		ResponseType: pago.ResponseJSON,
		Errors: map[int]pago.ErrorDecoder{
			404: newResourceNotFoundError,
			422: newHTTPValidationResponseError,
		},
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
