// Code generated by the Pago SDK generator. DO NOT EDIT.

package v2026_04

import (
	"encoding/json"
	"net/http"

	pago "github.com/pago-sh/pago-go"
)

// WebhookBenefitCreatedPayload
//
// Sent when a new benefit is created.
//
// **Discord & Slack support:** Basic
type WebhookBenefitCreatedPayload struct {
	Type      string  `json:"type"`
	Timestamp string  `json:"timestamp"`
	Data      Benefit `json:"data"`
}

// WebhookBenefitGrantCreatedPayload
//
// Sent when a new benefit grant is created.
//
// **Discord & Slack support:** Basic
type WebhookBenefitGrantCreatedPayload struct {
	Type      string              `json:"type"`
	Timestamp string              `json:"timestamp"`
	Data      BenefitGrantWebhook `json:"data"`
}

// WebhookBenefitGrantCycledPayload
//
// Sent when a benefit grant is cycled,
// meaning the related subscription has been renewed for another period.
//
// **Discord & Slack support:** Basic
type WebhookBenefitGrantCycledPayload struct {
	Type      string              `json:"type"`
	Timestamp string              `json:"timestamp"`
	Data      BenefitGrantWebhook `json:"data"`
}

// WebhookBenefitGrantRevokedPayload
//
// Sent when a benefit grant is revoked.
//
// **Discord & Slack support:** Basic
type WebhookBenefitGrantRevokedPayload struct {
	Type      string              `json:"type"`
	Timestamp string              `json:"timestamp"`
	Data      BenefitGrantWebhook `json:"data"`
}

// WebhookBenefitGrantUpdatedPayload
//
// Sent when a benefit grant is updated.
//
// **Discord & Slack support:** Basic
type WebhookBenefitGrantUpdatedPayload struct {
	Type      string              `json:"type"`
	Timestamp string              `json:"timestamp"`
	Data      BenefitGrantWebhook `json:"data"`
}

// WebhookBenefitUpdatedPayload
//
// Sent when a benefit is updated.
//
// **Discord & Slack support:** Basic
type WebhookBenefitUpdatedPayload struct {
	Type      string  `json:"type"`
	Timestamp string  `json:"timestamp"`
	Data      Benefit `json:"data"`
}

// WebhookCheckoutCreatedPayload
//
// Sent when a new checkout is created.
//
// **Discord & Slack support:** Basic
type WebhookCheckoutCreatedPayload struct {
	Type      string   `json:"type"`
	Timestamp string   `json:"timestamp"`
	Data      Checkout `json:"data"`
}

// WebhookCheckoutExpiredPayload
//
// Sent when a checkout expires.
//
// This event fires when a checkout reaches its expiration time without being completed.
// Developers can use this to send reminder emails or track checkout abandonment.
//
// **Discord & Slack support:** Basic
type WebhookCheckoutExpiredPayload struct {
	Type      string   `json:"type"`
	Timestamp string   `json:"timestamp"`
	Data      Checkout `json:"data"`
}

// WebhookCheckoutUpdatedPayload
//
// Sent when a checkout is updated.
//
// **Discord & Slack support:** Basic
type WebhookCheckoutUpdatedPayload struct {
	Type      string   `json:"type"`
	Timestamp string   `json:"timestamp"`
	Data      Checkout `json:"data"`
}

// WebhookCustomerCreatedPayload
//
// Sent when a new customer is created.
//
// A customer can be created:
//
// * After a successful checkout.
// * Programmatically via the API.
//
// **Discord & Slack support:** Basic
type WebhookCustomerCreatedPayload struct {
	Type      string   `json:"type"`
	Timestamp string   `json:"timestamp"`
	Data      Customer `json:"data"`
}

// WebhookCustomerDeletedPayload
//
// Sent when a customer is deleted.
//
// **Discord & Slack support:** Basic
type WebhookCustomerDeletedPayload struct {
	Type      string   `json:"type"`
	Timestamp string   `json:"timestamp"`
	Data      Customer `json:"data"`
}

// WebhookCustomerSeatAssignedPayload
//
// Sent when a new customer seat is assigned.
//
// This event is triggered when a seat is assigned to a customer by the organization.
// The customer will receive an invitation email to claim the seat.
type WebhookCustomerSeatAssignedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      CustomerSeat `json:"data"`
}

// WebhookCustomerSeatClaimedPayload
//
// Sent when a customer seat is claimed.
//
// This event is triggered when a customer accepts the seat invitation and claims their access.
type WebhookCustomerSeatClaimedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      CustomerSeat `json:"data"`
}

// WebhookCustomerSeatRevokedPayload
//
// Sent when a customer seat is revoked.
//
// This event is triggered when access to a seat is revoked, either manually by the organization or automatically when a subscription is canceled.
type WebhookCustomerSeatRevokedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      CustomerSeat `json:"data"`
}

// WebhookCustomerStateChangedPayload
//
// Sent when a customer state has changed.
//
// It's triggered when:
//
// * Customer is created, updated or deleted.
// * A subscription is created or updated.
// * A benefit is granted or revoked.
//
// **Discord & Slack support:** Basic
type WebhookCustomerStateChangedPayload struct {
	Type      string        `json:"type"`
	Timestamp string        `json:"timestamp"`
	Data      CustomerState `json:"data"`
}

// WebhookCustomerUpdatedPayload
//
// Sent when a customer is updated.
//
// This event is fired when the customer details are updated.
//
// If you want to be notified when a customer subscription or benefit state changes, you should listen to the `customer_state_changed` event.
//
// **Discord & Slack support:** Basic
type WebhookCustomerUpdatedPayload struct {
	Type      string   `json:"type"`
	Timestamp string   `json:"timestamp"`
	Data      Customer `json:"data"`
}

// WebhookMemberCreatedPayload
//
// Sent when a new member is created.
//
// A member represents an individual within a customer (team).
// This event is triggered when a member is added to a customer,
// either programmatically via the API or when an owner is automatically
// created for a new customer.
//
// **Discord & Slack support:** Basic
type WebhookMemberCreatedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Member `json:"data"`
}

// WebhookMemberDeletedPayload
//
// Sent when a member is deleted.
//
// This event is triggered when a member is removed from a customer.
// Any active seats assigned to the member will be automatically revoked.
//
// **Discord & Slack support:** Basic
type WebhookMemberDeletedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Member `json:"data"`
}

// WebhookMemberUpdatedPayload
//
// Sent when a member is updated.
//
// This event is triggered when member details are updated,
// such as their name or role within the customer.
//
// **Discord & Slack support:** Basic
type WebhookMemberUpdatedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Member `json:"data"`
}

// WebhookOrderCreatedPayload
//
// Sent when a new order is created.
//
// A new order is created when:
//
// * A customer purchases a one-time product. In this case, `billing_reason` is set to `purchase`.
// * A customer starts a subscription. In this case, `billing_reason` is set to `subscription_create`.
// * A subscription is renewed. In this case, `billing_reason` is set to `subscription_cycle`.
// * A subscription is upgraded or downgraded with an immediate proration invoice. In this case, `billing_reason` is set to `subscription_update`.
//
// > [!WARNING]
// > The order might not be paid yet, so the `status` field might be `pending`.
//
// **Discord & Slack support:** Full
type WebhookOrderCreatedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Order  `json:"data"`
}

// WebhookOrderPaidPayload
//
// Sent when an order is paid.
//
// When you receive this event, the order is fully processed and payment has been received.
//
// **Discord & Slack support:** Full
type WebhookOrderPaidPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Order  `json:"data"`
}

// WebhookOrderRefundedPayload
//
// Sent when an order is fully or partially refunded.
//
// **Discord & Slack support:** Full
type WebhookOrderRefundedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Order  `json:"data"`
}

// WebhookOrderUpdatedPayload
//
// Sent when an order is updated.
//
// An order is updated when:
//
// * Its status changes, e.g. from `pending` to `paid`.
// * It's refunded, partially or fully.
//
// **Discord & Slack support:** Full
type WebhookOrderUpdatedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Order  `json:"data"`
}

// WebhookOrganizationUpdatedPayload
//
// Sent when a organization is updated.
//
// **Discord & Slack support:** Basic
type WebhookOrganizationUpdatedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Organization `json:"data"`
}

// WebhookProductCreatedPayload
//
// Sent when a new product is created.
//
// **Discord & Slack support:** Basic
type WebhookProductCreatedPayload struct {
	Type      string  `json:"type"`
	Timestamp string  `json:"timestamp"`
	Data      Product `json:"data"`
}

// WebhookProductUpdatedPayload
//
// Sent when a product is updated.
//
// **Discord & Slack support:** Basic
type WebhookProductUpdatedPayload struct {
	Type      string  `json:"type"`
	Timestamp string  `json:"timestamp"`
	Data      Product `json:"data"`
}

// WebhookRefundCreatedPayload
//
// Sent when a refund is created regardless of status.
//
// **Discord & Slack support:** Full
type WebhookRefundCreatedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Refund `json:"data"`
}

// WebhookRefundUpdatedPayload
//
// Sent when a refund is updated.
//
// **Discord & Slack support:** Full
type WebhookRefundUpdatedPayload struct {
	Type      string `json:"type"`
	Timestamp string `json:"timestamp"`
	Data      Refund `json:"data"`
}

// WebhookSubscriptionActivePayload
//
// Sent when a subscription becomes active,
// whether because it's a new paid subscription or because payment was recovered.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionActivePayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionCanceledPayload
//
// Sent when a subscription is canceled.
// Customers might still have access until the end of the current period.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionCanceledPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionCreatedPayload
//
// Sent when a new subscription is created.
//
// When this event occurs, the subscription `status` might not be `active` yet, as we can still have to wait for the first payment to be processed.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionCreatedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionPastDuePayload
//
// Sent when a subscription payment fails and the subscription enters `past_due` status.
//
// This is a recoverable state - the customer can update their payment method to restore the subscription.
// Benefits may be revoked depending on the organization's grace period settings.
//
// If payment retries are exhausted, a `subscription.revoked` event will be sent.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionPastDuePayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionPausedPayload
//
// Sent when a subscription is paused and the customer temporarily loses access.
//
// No order is created while paused. The subscription resumes either on its
// scheduled resume date or when resumed manually, starting a new billing period.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionPausedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionResumedPayload
//
// Sent when a paused subscription resumes, restoring the customer's access.
//
// Resuming starts a new billing period and charges the customer immediately.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionResumedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionRevokedPayload
//
// Sent when a subscription is revoked and the user loses access immediately.
// Happens when the subscription is canceled or payment retries are exhausted (status becomes `unpaid`).
//
// For payment failures that can still be recovered, see `subscription.past_due`.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionRevokedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionUncanceledPayload
//
// Sent when a customer revokes a pending cancellation.
//
// When a customer cancels with "at period end", they retain access until the
// subscription would renew. During this time, they can change their mind and
// undo the cancellation. This event is triggered when they do so.
//
// **Discord & Slack support:** Full
type WebhookSubscriptionUncanceledPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookSubscriptionUpdatedPayload
//
// Sent when a subscription is updated. This event fires for all changes to the subscription, including renewals.
//
// If you want more specific events, you can listen to `subscription.active`, `subscription.canceled`, `subscription.past_due`, and `subscription.revoked`.
//
// To listen specifically for renewals, you can listen to `order.created` events and check the `billing_reason` field.
//
// **Discord & Slack support:** On cancellation, past due, and revocation. Renewals are skipped.
type WebhookSubscriptionUpdatedPayload struct {
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Data      Subscription `json:"data"`
}

// WebhookPayload is implemented by every webhook payload of this API
// version.
//
// Use a type switch to handle the events you care about:
//
//	switch payload := event.(type) {
//	case *WebhookBenefitCreatedPayload:
//		// ...
//	}
type WebhookPayload interface {
	// EventType returns the "type" field of the payload.
	EventType() string

	isWebhookEvent()
}

// EventType returns "benefit.created".
func (e *WebhookBenefitCreatedPayload) EventType() string { return "benefit.created" }

func (e *WebhookBenefitCreatedPayload) isWebhookEvent() {}

// EventType returns "benefit.updated".
func (e *WebhookBenefitUpdatedPayload) EventType() string { return "benefit.updated" }

func (e *WebhookBenefitUpdatedPayload) isWebhookEvent() {}

// EventType returns "benefit_grant.created".
func (e *WebhookBenefitGrantCreatedPayload) EventType() string { return "benefit_grant.created" }

func (e *WebhookBenefitGrantCreatedPayload) isWebhookEvent() {}

// EventType returns "benefit_grant.cycled".
func (e *WebhookBenefitGrantCycledPayload) EventType() string { return "benefit_grant.cycled" }

func (e *WebhookBenefitGrantCycledPayload) isWebhookEvent() {}

// EventType returns "benefit_grant.revoked".
func (e *WebhookBenefitGrantRevokedPayload) EventType() string { return "benefit_grant.revoked" }

func (e *WebhookBenefitGrantRevokedPayload) isWebhookEvent() {}

// EventType returns "benefit_grant.updated".
func (e *WebhookBenefitGrantUpdatedPayload) EventType() string { return "benefit_grant.updated" }

func (e *WebhookBenefitGrantUpdatedPayload) isWebhookEvent() {}

// EventType returns "checkout.created".
func (e *WebhookCheckoutCreatedPayload) EventType() string { return "checkout.created" }

func (e *WebhookCheckoutCreatedPayload) isWebhookEvent() {}

// EventType returns "checkout.expired".
func (e *WebhookCheckoutExpiredPayload) EventType() string { return "checkout.expired" }

func (e *WebhookCheckoutExpiredPayload) isWebhookEvent() {}

// EventType returns "checkout.updated".
func (e *WebhookCheckoutUpdatedPayload) EventType() string { return "checkout.updated" }

func (e *WebhookCheckoutUpdatedPayload) isWebhookEvent() {}

// EventType returns "customer.created".
func (e *WebhookCustomerCreatedPayload) EventType() string { return "customer.created" }

func (e *WebhookCustomerCreatedPayload) isWebhookEvent() {}

// EventType returns "customer.deleted".
func (e *WebhookCustomerDeletedPayload) EventType() string { return "customer.deleted" }

func (e *WebhookCustomerDeletedPayload) isWebhookEvent() {}

// EventType returns "customer.state_changed".
func (e *WebhookCustomerStateChangedPayload) EventType() string { return "customer.state_changed" }

func (e *WebhookCustomerStateChangedPayload) isWebhookEvent() {}

// EventType returns "customer.updated".
func (e *WebhookCustomerUpdatedPayload) EventType() string { return "customer.updated" }

func (e *WebhookCustomerUpdatedPayload) isWebhookEvent() {}

// EventType returns "customer_seat.assigned".
func (e *WebhookCustomerSeatAssignedPayload) EventType() string { return "customer_seat.assigned" }

func (e *WebhookCustomerSeatAssignedPayload) isWebhookEvent() {}

// EventType returns "customer_seat.claimed".
func (e *WebhookCustomerSeatClaimedPayload) EventType() string { return "customer_seat.claimed" }

func (e *WebhookCustomerSeatClaimedPayload) isWebhookEvent() {}

// EventType returns "customer_seat.revoked".
func (e *WebhookCustomerSeatRevokedPayload) EventType() string { return "customer_seat.revoked" }

func (e *WebhookCustomerSeatRevokedPayload) isWebhookEvent() {}

// EventType returns "member.created".
func (e *WebhookMemberCreatedPayload) EventType() string { return "member.created" }

func (e *WebhookMemberCreatedPayload) isWebhookEvent() {}

// EventType returns "member.deleted".
func (e *WebhookMemberDeletedPayload) EventType() string { return "member.deleted" }

func (e *WebhookMemberDeletedPayload) isWebhookEvent() {}

// EventType returns "member.updated".
func (e *WebhookMemberUpdatedPayload) EventType() string { return "member.updated" }

func (e *WebhookMemberUpdatedPayload) isWebhookEvent() {}

// EventType returns "order.created".
func (e *WebhookOrderCreatedPayload) EventType() string { return "order.created" }

func (e *WebhookOrderCreatedPayload) isWebhookEvent() {}

// EventType returns "order.paid".
func (e *WebhookOrderPaidPayload) EventType() string { return "order.paid" }

func (e *WebhookOrderPaidPayload) isWebhookEvent() {}

// EventType returns "order.refunded".
func (e *WebhookOrderRefundedPayload) EventType() string { return "order.refunded" }

func (e *WebhookOrderRefundedPayload) isWebhookEvent() {}

// EventType returns "order.updated".
func (e *WebhookOrderUpdatedPayload) EventType() string { return "order.updated" }

func (e *WebhookOrderUpdatedPayload) isWebhookEvent() {}

// EventType returns "organization.updated".
func (e *WebhookOrganizationUpdatedPayload) EventType() string { return "organization.updated" }

func (e *WebhookOrganizationUpdatedPayload) isWebhookEvent() {}

// EventType returns "product.created".
func (e *WebhookProductCreatedPayload) EventType() string { return "product.created" }

func (e *WebhookProductCreatedPayload) isWebhookEvent() {}

// EventType returns "product.updated".
func (e *WebhookProductUpdatedPayload) EventType() string { return "product.updated" }

func (e *WebhookProductUpdatedPayload) isWebhookEvent() {}

// EventType returns "refund.created".
func (e *WebhookRefundCreatedPayload) EventType() string { return "refund.created" }

func (e *WebhookRefundCreatedPayload) isWebhookEvent() {}

// EventType returns "refund.updated".
func (e *WebhookRefundUpdatedPayload) EventType() string { return "refund.updated" }

func (e *WebhookRefundUpdatedPayload) isWebhookEvent() {}

// EventType returns "subscription.active".
func (e *WebhookSubscriptionActivePayload) EventType() string { return "subscription.active" }

func (e *WebhookSubscriptionActivePayload) isWebhookEvent() {}

// EventType returns "subscription.canceled".
func (e *WebhookSubscriptionCanceledPayload) EventType() string { return "subscription.canceled" }

func (e *WebhookSubscriptionCanceledPayload) isWebhookEvent() {}

// EventType returns "subscription.created".
func (e *WebhookSubscriptionCreatedPayload) EventType() string { return "subscription.created" }

func (e *WebhookSubscriptionCreatedPayload) isWebhookEvent() {}

// EventType returns "subscription.past_due".
func (e *WebhookSubscriptionPastDuePayload) EventType() string { return "subscription.past_due" }

func (e *WebhookSubscriptionPastDuePayload) isWebhookEvent() {}

// EventType returns "subscription.paused".
func (e *WebhookSubscriptionPausedPayload) EventType() string { return "subscription.paused" }

func (e *WebhookSubscriptionPausedPayload) isWebhookEvent() {}

// EventType returns "subscription.resumed".
func (e *WebhookSubscriptionResumedPayload) EventType() string { return "subscription.resumed" }

func (e *WebhookSubscriptionResumedPayload) isWebhookEvent() {}

// EventType returns "subscription.revoked".
func (e *WebhookSubscriptionRevokedPayload) EventType() string { return "subscription.revoked" }

func (e *WebhookSubscriptionRevokedPayload) isWebhookEvent() {}

// EventType returns "subscription.uncanceled".
func (e *WebhookSubscriptionUncanceledPayload) EventType() string { return "subscription.uncanceled" }

func (e *WebhookSubscriptionUncanceledPayload) isWebhookEvent() {}

// EventType returns "subscription.updated".
func (e *WebhookSubscriptionUpdatedPayload) EventType() string { return "subscription.updated" }

func (e *WebhookSubscriptionUpdatedPayload) isWebhookEvent() {}

// WebhookEventTypes lists every webhook event type this SDK version knows.
var WebhookEventTypes = map[string]struct{}{
	"benefit.created":         {},
	"benefit.updated":         {},
	"benefit_grant.created":   {},
	"benefit_grant.cycled":    {},
	"benefit_grant.revoked":   {},
	"benefit_grant.updated":   {},
	"checkout.created":        {},
	"checkout.expired":        {},
	"checkout.updated":        {},
	"customer.created":        {},
	"customer.deleted":        {},
	"customer.state_changed":  {},
	"customer.updated":        {},
	"customer_seat.assigned":  {},
	"customer_seat.claimed":   {},
	"customer_seat.revoked":   {},
	"member.created":          {},
	"member.deleted":          {},
	"member.updated":          {},
	"order.created":           {},
	"order.paid":              {},
	"order.refunded":          {},
	"order.updated":           {},
	"organization.updated":    {},
	"product.created":         {},
	"product.updated":         {},
	"refund.created":          {},
	"refund.updated":          {},
	"subscription.active":     {},
	"subscription.canceled":   {},
	"subscription.created":    {},
	"subscription.past_due":   {},
	"subscription.paused":     {},
	"subscription.resumed":    {},
	"subscription.revoked":    {},
	"subscription.uncanceled": {},
	"subscription.updated":    {},
}

// ParseWebhookEvent decodes an already verified webhook body into its typed
// payload.
func ParseWebhookEvent(body []byte) (WebhookPayload, error) {
	var envelope struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, pago.NewWebhookError("failed to parse webhook payload", err)
	}

	switch envelope.Type {
	case "benefit.created":
		payload := new(WebhookBenefitCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "benefit.updated":
		payload := new(WebhookBenefitUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "benefit_grant.created":
		payload := new(WebhookBenefitGrantCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "benefit_grant.cycled":
		payload := new(WebhookBenefitGrantCycledPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "benefit_grant.revoked":
		payload := new(WebhookBenefitGrantRevokedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "benefit_grant.updated":
		payload := new(WebhookBenefitGrantUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "checkout.created":
		payload := new(WebhookCheckoutCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "checkout.expired":
		payload := new(WebhookCheckoutExpiredPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "checkout.updated":
		payload := new(WebhookCheckoutUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer.created":
		payload := new(WebhookCustomerCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer.deleted":
		payload := new(WebhookCustomerDeletedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer.state_changed":
		payload := new(WebhookCustomerStateChangedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer.updated":
		payload := new(WebhookCustomerUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer_seat.assigned":
		payload := new(WebhookCustomerSeatAssignedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer_seat.claimed":
		payload := new(WebhookCustomerSeatClaimedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "customer_seat.revoked":
		payload := new(WebhookCustomerSeatRevokedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "member.created":
		payload := new(WebhookMemberCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "member.deleted":
		payload := new(WebhookMemberDeletedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "member.updated":
		payload := new(WebhookMemberUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "order.created":
		payload := new(WebhookOrderCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "order.paid":
		payload := new(WebhookOrderPaidPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "order.refunded":
		payload := new(WebhookOrderRefundedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "order.updated":
		payload := new(WebhookOrderUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "organization.updated":
		payload := new(WebhookOrganizationUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "product.created":
		payload := new(WebhookProductCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "product.updated":
		payload := new(WebhookProductUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "refund.created":
		payload := new(WebhookRefundCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "refund.updated":
		payload := new(WebhookRefundUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.active":
		payload := new(WebhookSubscriptionActivePayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.canceled":
		payload := new(WebhookSubscriptionCanceledPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.created":
		payload := new(WebhookSubscriptionCreatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.past_due":
		payload := new(WebhookSubscriptionPastDuePayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.paused":
		payload := new(WebhookSubscriptionPausedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.resumed":
		payload := new(WebhookSubscriptionResumedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.revoked":
		payload := new(WebhookSubscriptionRevokedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.uncanceled":
		payload := new(WebhookSubscriptionUncanceledPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	case "subscription.updated":
		payload := new(WebhookSubscriptionUpdatedPayload)
		if err := json.Unmarshal(body, payload); err != nil {
			return nil, pago.NewWebhookError("failed to parse webhook payload", err)
		}
		return payload, nil
	}
	return nil, pago.NewWebhookUnknownTypeError(envelope.Type)
}

// ValidateEvent verifies the signature of a raw webhook request and
// returns its typed payload.
//
//	event, err := v2026_04.ValidateEvent(body, request.Header, secret)
//
// It returns a *pago.WebhookVerificationError when the signature does not
// match, and a *pago.WebhookUnknownTypeError when the event type is unknown to
// this SDK version.
func ValidateEvent(body []byte, headers http.Header, secret string) (WebhookPayload, error) {
	if _, err := pago.ValidateWebhook(body, headers, secret, WebhookEventTypes); err != nil {
		return nil, err
	}
	return ParseWebhookEvent(body)
}
